### ISSUE TITLE
NonInteractive Mode

### ISSUE THREAD

**Issue by JAmler** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#101]
Hello,

I'm trying to run this command via DevOps, so I have to run it in NonInteractive Mode. But the command opens like 4 windows, where I have to confirm, that I really want to run it. As neither the -confirm nor the -force parameter is integrated I can't find a way to run it without the failure:

Set-SPOTenant : Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available.

Is there another way to get it working in NonIneractive mode?

Best regards!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da2c76d9-43fd-c631-e6d4-69852b376444
* Version Independent ID: b8ae322e-d3a7-9759-8407-b20f7469cad7
* Content: [Set-SPOTenant (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/Set-SPOTenant?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Hello @JAmler what is the parameter that is asking you for confirmation?

**Comment by yogkumgit** [comment]
@JAmler reply.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and digging deep into it.  @JAmler We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
