### ISSUE TITLE
Terrible documentation

### ISSUE THREAD

**Issue by SharePointGuys** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#103]
[Enter feedback here]
This is a terrible spec that is helpless. No many detailed explanations. Of course, people can argue this point.

For example, in this article, search the following sentence:
In the page For more information, type the following command: get-help about_commonparameters

Then go to PowerShell environment and type the following cmdlet:
get-help Disable-SPFeature -detailed

Exact same content will be shown up.

Sigh...................

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a99664-cc7f-d789-c5fd-488e0d73874d
* Version Independent ID: 2d555636-8122-3ab0-0ac0-9fe656a9555b
* Content: [Disable-SPFeature (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/disable-spfeature?view=sharepoint-server-ps)
* Content Source: [sharepoint/sharepoint-server-ps/sharepoint-server/Disable-SPFeature.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-server-ps/sharepoint-server/Disable-SPFeature.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by tseward** [comment]
Remember that SharePoint pre-SE doesn't pick up cmdlet documentation from online -- what you see is what you get in-product, so the documentation here could be better than what you see when you run `get-help`.

With that said, yes this cmdlet doc needs improvement. For one, it should not use short hand in the example (i.e., it should not use `%`) and the `-Identity` description explicitly references the 14 hive which wouldn't necessarily be correct for 2013 and higher.
