### ISSUE TITLE
Add-PnPNavigationNode - EXAMPLE 6 - missing slash in url

### ISSUE THREAD

**Issue by shnidi** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#109]
Add-PnPNavigationNode - EXAMPLE 6 - missing slash in url

This does not create a label:
```
Add-PnPNavigationNode -Title "Label" -Location "TopNavigationBar" -Url "http://linkless.header"
```
It should be:
```
Add-PnPNavigationNode -Title "Label" -Location "TopNavigationBar" -Url "http://linkless.header/"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88eb5100-4508-3d09-7e6e-41aa3ce25b26
* Version Independent ID: 3e7b7949-0d2a-3569-ad41-72406a9e1ad8
* Content: [Add-PnPNavigationNode (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpnavigationnode?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPNavigationNode.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPNavigationNode.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello, how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @shnidi Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
