### ISSUE TITLE
DefaultLinkPermission value None

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#113]
Can you please clarify what None is supposed to mean for DefaultLinkPermission value? On a "fresh" tenant, with None showing in PowerShell, the UI displays a value of "Edit" instead, so I suppose we should assume that "Edit" is sort of a default value? I guess we can argue on the semantics of "default" here, but as Edit is the value pre-populated in the UI, it gets set automatically upon making any change (unless you of course manually set it to View).

Or let me ask the question a different way, if the value of DefaultLinkPermission is set to None as reported by PowerShell, what kind of link the users will be able to created, Edit or View-only?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da2c76d9-43fd-c631-e6d4-69852b376444
* Version Independent ID: b8ae322e-d3a7-9759-8407-b20f7469cad7
* Content: [Set-SPOTenant (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Thanks for your feedback @michevnew
