### ISSUE TITLE
Remove-PnPPlannerBucket not working with BucketId and Identity parameters

### ISSUE THREAD

**Issue by gavdgavd** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#119]
The given syntax:

Remove-PnPPlannerBucket
      -BucketId <String>
      -Identity <PlannerBucketPipeBind>
       [-WhatIf]
      [-Confirm]
      [<CommonParameters>]

doesn't work using these two parameters. Additionally, it makes no sense to use the BucketId and the Identifier at the same time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0e7e707-a92b-9f4b-8b88-06d7c6f89b16
* Version Independent ID: 666fe154-f581-769e-ed79-234b44e22d0b
* Content: [Remove-PnPPlannerBucket (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/remove-pnpplannerbucket?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPPlannerBucket.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-pnp/Remove-PnPPlannerBucket.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @gavdgavd 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @gavdgavd Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
