### ISSUE TITLE
Title of add-pnpplannerbucket should be with capital initial letters

### ISSUE THREAD

**Issue by gavdgavd** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#120]
To maintain a consequent style on all cmdlets, the title of "add-pnpplannerbucket" must be "Add-PnPPlannerBucket". Also in the Syntax section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02e13295-48e2-e58b-e291-cf82d77b4a5b
* Version Independent ID: 256a1c5e-2507-7c51-3157-cf32a4daba49
* Content: [add-pnpplannerbucket (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpplannerbucket?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPPlannerBucket.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-pnp/Add-PnPPlannerBucket.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @gavdgavd 

how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @gavdgavd Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
