### ISSUE TITLE
-ArchiveUrl - what does archiving mean?

### ISSUE THREAD

**Issue by AlexRademeyer** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#127]
What do you mean (technically) by "archive"?
Does archiving change or remove any content, permissions etc?
Any retention/ deletion policies? etc?

or is the content completely unchanged, just found at a different link?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1c4fb8b-6cc5-4214-0d39-470a0d209282
* Version Independent ID: b9b7cb69-2ff4-b8bb-929f-d73b22ff7561
* Content: [Invoke-SPOSiteSwap (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/invoke-spositeswap?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Invoke-SPOSiteSwap.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Invoke-SPOSiteSwap.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @WayneEwington
* Microsoft Alias: **waynewin**

**Comment by WayneEwington** [comment]
The term "archive" in this context is that the content is completely unchanged and is just at a different URL location.

**Comment by get-itips** [comment]
Thanks for the clarification @WayneEwington

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and confirming this explanation. @AlexRademeyer Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
