### ISSUE TITLE
"Tip"-section in top of all pages is shown in lists and makes them harder to navigate

### ISSUE THREAD

**Issue by 2ndcahl** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#129]
On the Cmdlet Reference page, all cmdlet are listed and shows the short description of each cmdlet.
Problem is that in this section there is also added a "Tip"-section, that shows up in the list. This tip is now shown in the list and makes it harder to read the list. Se attached screenshot.
Suggestion: For all cmdlet, remove the tip-section from all pages or move it to another part (like "Description") of each page that is not shown in the Cmdlet Reference page.

![image](https://user-images.githubusercontent.com/23452725/149094319-dd5642ae-dba5-49ea-b01f-280c8b389f92.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74b526f5-39fd-b32c-eee7-50304a6eed9f
* Version Independent ID: 519a4440-5762-67f0-e00b-26fa9e321253
* Content: [PnP.Powershell Module](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/sharepoint-pnp.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-pnp/sharepoint-pnp.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @erwinvanhunen
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello,
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @2ndcahl Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
