### ISSUE TITLE
Please make it clear that cmdlet does NOT work for managed metadata

### ISSUE THREAD

**Issue by zumiek** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#130]
[Enter feedback here]

Doesn't work for managed metadata.
You should make that clear since the bug has been there since 2019...
https://github.com/pnp/PnP-PowerShell/issues/1978
https://github.com/pnp/powershell/issues/1110
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1700b68e-9656-c90e-26a1-3143d28af5fe
* Version Independent ID: 28f5be7f-bb74-e39d-bd8e-05c116ba8f74
* Content: [Clear-PnPDefaultColumnValues (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/clear-pnpdefaultcolumnvalues?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Clear-PnPDefaultColumnValues.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-pnp/Clear-PnPDefaultColumnValues.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by jackpoz** [comment]
PR https://github.com/pnp/pnpframework/pull/576 fixes the issue of managed metadata case not working, making this issue obsolete once the PR gets merged and a new version on PnP Powershell is released

**Comment by get-itips** [comment]
Hello @zumiek 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @jackpoz Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
