### ISSUE TITLE
Add GCC High and DoD clarity to to the Connect-SPOService article.

### ISSUE THREAD

**Issue by jarossnd** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#132]
There is some confusion regarding this article with the `-region ITAR` parameter and value. It should be called out that ITAR should be used for GCC High and DoD tenants. Otherwise, standard GCC customers might attempt to use `-region ITAR` when it is actually for GCC High and DoD.

I also recommend adding an Example 4 to this article to illustrate how a GCC High or DoD customer would connect to their SharePoint Online tenant:

-----------------------EXAMPLE 4-----------------------------
``` PowerShell
Connect-SPOService -Url https://contoso-admin.sharepoint.us -Region ITAR
```
Example 4 shows how a GCC High / DoD SharePoint Online Administrator or Global Administrator with credential admin@contoso.com connects to a SharePoint Online Administration Center that has the URL https://contoso-admin.sharepoint.us.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d3c1e49-2acd-707a-33b2-2abe705fa123
* Version Independent ID: a6afec72-10c8-84c9-9435-74602c30a3c0
* Content: [Connect-SPOService (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/connect-sposervice?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Hello @jarossnd Jason, I am looking into this, thanks
