### ISSUE TITLE
Can't Only Change Title

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#133]
Article leads user to believe they can change the site URL, title, or both; however, when running the command it forces you to specify the value for -NewSiteUrl. So you're not able to run the command to change the site title, thereby leaving the url alone. Would be nice.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f36c1f06-85b4-9a6a-28fc-115522dcb1c4
* Version Independent ID: 7e041b3f-dffb-00bf-c00d-b9b071a7b99a
* Content: [Start-SPOSiteRename (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/start-spositerename?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteRename.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteRename.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by chhaya-sharma9** [comment]
Thanks for the feedback. The capability of Start-SPOSiteRename to rename a Site URL, is detailed in the public documentation here - https://docs.microsoft.com/en-us/sharepoint/change-site-address 
You could change the site display name independently from the SPO Admin Center.

**Comment by yogkumgit** [comment]
@pyoungberg Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
