### ISSUE TITLE
Copy-PnPList - Source and Destination are different tenants

### ISSUE THREAD

**Issue by robertcaretta** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#137]
Can this work between tenants?  For example TEST and PROD.
Can you provide an example of how that would work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cd10ab-8c68-5739-2927-fb29a4c2619c
* Version Independent ID: b2c028f5-84e1-8bd8-39d7-92eadefdeaa0
* Content: [Copy-PnPList (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/copy-pnplist?view=sharepoint-ps#examples)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Copy-PnPList.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-pnp/Copy-PnPList.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by robertcaretta** [comment]
Also example #4 on this page has a type with the variables.

**Comment by get-itips** [comment]
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!
