### ISSUE TITLE
Feature registration for spfx solution not setting attributes properly

### ISSUE THREAD

**Issue by Chris-dot-net** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#149]
Every App will be registered as Feature, but the title attribute from package-solution.json will be ignored. So if there is a need to remove the features w/o removing the app first, in some cases like spfx web part solutions there is no way to get the id in forehand.

This results in features (via get-pnpfeature) to have id and displayname identical.
![image](https://user-images.githubusercontent.com/73933965/152332794-1a41a953-154a-4e0d-85cf-d5ae18364032.png)

I guess it's a bug, because it is shown correctly in UI with feature title.

**Comment by get-itips** [comment]
Hello @Chris-dot-net 

Can you please put here the URL of the article you opened the issue for?

Thank you

**Comment by yogkumgit** [comment]
@Chris-dot-net We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
