### ISSUE TITLE
Unable to run Connect-PnPOnline using Microsoft Service Account

### ISSUE THREAD

**Issue by lipalath-ms** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#156]
I created a non-people service account via https://coreidentity.microsoft.com/ last year. Because I forgot the password, I reset it and created a new password. When I try to run Connect-PnPOnline, I see an error "The sign-in name or password does not match one in the Microsoft account system". Why is that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c26cf04-dd81-06b0-0156-fe5c9555ab77
* Version Independent ID: 5a53923c-0be4-aea7-7e07-bb1a29c820c8
* Content: [Connect-PnPOnline (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/connect-pnponline?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPOnline.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-pnp/Connect-PnPOnline.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello!
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @lipalath-ms Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
