### ISSUE TITLE
Please correct the format of the allowed list as it accepts comma as the delimiter instead of space as mentioned in the article.

### ISSUE THREAD

**Issue by subhenduroy91** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#161]
[Enter feedback here]

The following should be the correct format:

-SharingAllowedDomainList
Specifies a list of email domains that is allowed for sharing with the external collaborators. Use the comma character as the delimiter for entering multiple values. For example, "contoso.com,fabrikam.com". Effective when SharingDomainRestrictionMode is set to AllowList.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9f61cca-e123-bcbb-9c84-96e8edf30fd7
* Version Independent ID: b7b8d0ea-c18f-f7dd-e495-a93a41f905d9
* Content: [Set-PnPTenantSite (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnptenantsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPTenantSite.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPTenantSite.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @subhenduroy91 

how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @subhenduroy91 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
