### ISSUE TITLE
Headline missing SPO in Unlock-SensitivityLabelEncryptedFile 

### ISSUE THREAD

**Issue by ChristianJBergstrom** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#169]
[Hi, please update

Unlock-SensitivityLabelEncryptedFile

To

Unlock-**SPO**SensitivityLabelEncryptedFile

And also under the Syntax headline.

Thanks! ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dfb9a14-a275-539b-3af3-600227eedfe7
* Version Independent ID: 9f6c1b4d-7130-1d4c-d623-39c4e4d98f13
* Content: [Unlock-SensitivityLabelEncryptedFile (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/unlock-sposensitivitylabelencryptedfile?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Unlock-SPOSensitivityLabelEncryptedFile.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Unlock-SPOSensitivityLabelEncryptedFile.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Sanjoyan
* Microsoft Alias: **samust**

**Comment by get-itips** [comment]
Thanks for your feedback!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and updating the documentation with PR. @ChristianJBergstrom Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
