### ISSUE TITLE
WARNING: Consider using -Interactive instead

### ISSUE THREAD

**Issue by Peter-Wxin** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#170]
> Notice: if you use multi-factor authentication on your tenant, use
PowerShell
Connect-PnPOnline -Url https://yoursite.sharepoint.com -UseWebLogin

It prompts: "WARNING: Consider using -Interactive instead, which provides better functionality. See the documentation at https://pnp.github.io/powershell/cmdlets/Connect-PnPOnline.html#interactive-login-for-multi-factor-authentication" when running the command line. So which exactly do you recommend?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e257652-6b19-287b-7f39-21c2a0909c09
* Version Independent ID: 10c59abb-83b5-1ae4-2008-0a53e9ca952e
* Content: [PnP PowerShell Overview](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets)
* Content Source: [sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @Peter-Wxin 

how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!
