### ISSUE TITLE
Referenced Module

### ISSUE THREAD

**Issue by MSGRRojas** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#188]
On the Connect-SPOService page (https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/connect-sposervice?view=sharepoint-ps) it refers to Module: SharePointOnlinePowerShell which links to (https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/?view=sharepoint-ps).  
However, this is a bit misleading as typically when you're looking for a CMDLET, you see the required module and then Install-Module SharePointOnlinePowerShell which of course fails.

Can you update the link (I believe it's pulling from sharepointonline.xml) and at a minimum change the display to refer to Microsoft.Online.SharePoint.PowerShell

![image](https://user-images.githubusercontent.com/67468515/158847527-9838b20c-762e-40ca-9110-0d74e1a6bea9.png)

Thank you.  I'm available to discuss (greg.rojas@microsoft.com)

**Comment by yogkumgit** [comment]
@get-itips Please update. Thanks

**Comment by traya1** [comment]
Hi @[yogkumgit](https://github.com/yogkumgit),

@get-itips reached out to me for assistance, I have not found a solution to the issue but am still looking into it.

**Comment by MSGRRojas** [comment]
> Hi @[yogkumgit](https://github.com/yogkumgit),
> 
> @get-itips reached out to me for assistance, I have not found a solution to the issue but am still looking into it.

Thank you. Appreciate you all looking into this.

**Comment by get-itips** [comment]
Looks like it is fixed now
