### ISSUE TITLE
Update Set-SPOTenant to include OneDriveLoopSharingCapability

### ISSUE THREAD

**Issue by jarossnd** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#197]
We need documentation for:

`Set-SPOTenant -OneDriveLoopSharingCapability ExternalUserAndGuestSharing`

as described on the following article:

https://support.microsoft.com/en-us/office/enable-microsoft-whiteboard-for-your-organization-1caaa2e2-5c18-4bdf-b878-2d98f1da4b24

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da2c76d9-43fd-c631-e6d4-69852b376444
* Version Independent ID: b8ae322e-d3a7-9759-8407-b20f7469cad7
* Content: [Set-SPOTenant (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by jarossnd** [comment]
This issue might be a duplicate of https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/issues/182 which was opened > 2 weeks ago but no movement.

**Comment by get-itips** [comment]
Hello @jarossnd thanks for your feedback
