### ISSUE TITLE
Connect-sposervice is slow

### ISSUE THREAD

**Issue by roggyuk** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#198]
When running connect-sposervice with credentials stored in a variable its taking almost 2 minutes to connect.

**Comment by get-itips** [comment]
Hello @roggyuk 
How are you?
Even though, here, we are limited to **documentation** issues and fixes, I tested and connected in a couple of seconds, the best in your scenario would be to update to the latest version of the module and/or open a support ticket from your tenant.
Hope this information helps you!

@yogkumgit
