### ISSUE TITLE
Can't rename a site

### ISSUE THREAD

**Issue by Ofer-Gal** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#215]
I issue the command:
```
Start-SPOSiteRename -Identity $projectURL -NewSiteUrl "https://ecgmcdev.sharepoint.com/teams/historic0100009" -NewSiteTitle "Historic proposals" 
```
And get error :"The Microsoft 365 group for https://ecgmcaz.sharepoint.com/teams/0100.009 couldn't be found" 
So I try to set the 365 group with:
```
Set-SPOSiteOffice365Group -Site https://ecgmcaz.sharepoint.com/teams/0100.009 -DisplayName "0100.009 ECG Proposals" -Alias "0100.009@ecgmcAZ.onmicrosoft.com"
```
but get error Set-SPOSiteOffice365Group : This site already has an O365 Group attached.

How do I get out of the catch 22 ? :-)

**Comment by get-itips** [comment]
Hello @Ofer-Gal 

How are you?

I noticed the domain part of the URL for NewSiteUrl in your example is different from the one in the error, was that a typo?

>You can change only the address of the site within the URL, for example:
https://contoso.sharepoint.com/sites/projectx
to https://contoso.sharepoint.com/sites/projecty


https://docs.microsoft.com/en-US/sharepoint/change-site-address?WT.mc_id=365AdminCSH_spo

**Comment by Ofer-Gal** [comment]
Good catch. thanks
at the end I could not create new one instead of the renamed one because we have a retention policy that does not allow deleting sites. (rename is delete for SPO, go figure)

**Comment by get-itips** [comment]
@Ofer-Gal Thanks for returning and sharing your feedback!
