### ISSUE TITLE
Graph API 500 Internal error

### ISSUE THREAD

**Issue by ganlbarone** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#219]
Hello, 
I am using the below function to try and page through all SharePoint sites. The endpoint ignores top which is annoying, it seems to only return a max of 500 sites so that is what I set it to. Other than that the query is really rather basic, just return everything. The code then pages through until completion. I keep running into an internal server error and I am wondering how I can get help from someone internal to explain. There is no official support channel for Graph that I am aware of. Thanks.

![image](https://user-images.githubusercontent.com/31355460/162215369-85b80783-2b10-48f9-8c2d-384cc83a0f03.png)

```
Function DumpSharePointGraph(){
    $sharePointSites = @()
    try{
        $formaturi = "https://graph.microsoft.com/v1.0/sites?top=500&search=*"
        $data = Invoke-RestMethod -Method Get -Uri $formaturi -Headers $global:GraphHeader -ContentType "application/json" -ErrorAction Stop
        $sharePointSites += $data.value
        while(1){
            if($data.'@odata.nextLink'.Length -gt 1){
                $nextLink = $data.'@odata.nextLink'
                Write-Host "Getting next $($data.value.count) sites at $nextLink" -ForegroundColor Green
                $data = Invoke-RestMethod -Method Get -Uri $nextLink -Headers $global:GraphHeader -ContentType "application/json" -ErrorAction Stop
                $sharePointSites += $data.value
            }else{
                Write-Host "No sites left, exiting loop." -ForegroundColor Cyan
                break
            }
        }
        $global:GraphSharePointSites = $sharePointSites
        return $sharePointSites 
    }catch{
        $errorM = $_.exception.message
        Write-Host "Error On SharePoint: $errorM" -ForegroundColor Red
        RecursiveEmail "" "We ran into an error getting all sites:<br>$errorM" "O365 Master Loop - Error" 0
        $global:GraphSharePointSites = $sharePointSites
        return $sharePointSites
    }
}
```

**Comment by get-itips** [comment]
Hello @ganlbarone 
Here, we are limited to documentation fixes, is there any specific article under this repository that you feel needs a fix?
Your inquiry seems better suited for support, if you open a support request from your tenant, they might be able to help answer your inquiry. thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @ganlbarone Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
