### ISSUE TITLE
In example 1 and 2 of Upgrade-SPSite the description is same. However in the Upgrade-SPSite https://<site name>/sites/testsite -VersionUpgrade  it should be version to version upgrade.

### ISSUE THREAD

**Issue by SakshiAdlakha** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#229]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c2096ea-5309-70b0-849b-2aa2419504a6
* Version Independent ID: c5a7f49a-764c-e800-e9d2-54ccc0a515c6
* Content: [Upgrade-SPSite (SharePointServer)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/upgrade-spsite?view=sharepoint-ps&preserve-view=true)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Upgrade-SPSite.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-server/Upgrade-SPSite.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Thanks for your feedback @SakshiAdlakha
