### ISSUE TITLE
Enable-SPOCommSite not working

### ISSUE THREAD

**Issue by ahamin01** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#230]
Running the below command doesn't show any error, but it also doesn't convert the site completely into a Communication site. For example, page Full-Width section is missing, top navigation is still shown, and horizontal navigation is not in place. The only change is that a new homepage is created with one Full-Width section, but it's not possible to add additional Full-Width sections in this new homepage

`Enable-SPOCommSite -SiteUrl https://contoso.sharepoint.com`

Microsoft.Online.SharePoint.PowerShell Module version is 16.0.21213.12000

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cc9a3da-e451-85a0-a093-ca081c662e20
* Version Independent ID: a6989bf6-418d-a2c6-0323-d23b629fcd26
* Content: [Enable-SPOCommSite (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/enable-spocommsite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Enable-SPOCommSite.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Enable-SPOCommSite.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Hello @ahamin01 how are you? hope you are doing good
So I can reproduce to understand if we need to adjust documentation (we are limited only to documentation fixes), can you please confirm you have followed this requirements https://docs.microsoft.com/en-us/sharepoint/modernize-classic-team-site

Thank you

**Comment by get-itips** [comment]
@ahamin01 Hello, could you see my last comment here? Thanks

**Comment by ahamin01** [comment]
Hello @get-itips,

Yes, indeed. I followed that article and ensured that all the below points are met. I am even testing this on new sites, but with no hope

- The site template is STS#0
- The site is top-level site in the site collection.
- The user who runs the PowerShell cmdlet is a site collection admin and also tenant global admin.
- The SharePoint Server Publishing Infrastructure is not enabled and has never been enabled on the site (I even tested running the command on new site).

The cmdlet does some stuff, but not all. For example, it creates a new page and makes it the home page of the site, but somehow Full-Width sections are not available to be added to the site pages :-(

**Comment by get-itips** [comment]
Hello @ahamin01 
Thanks for clarifying, in that case, as here we are limited to **documentation** changes and improvements, the best would be to open a support request from your tenant, support services will be able to help you in your specific scenario.
Thank you

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @ahamin01 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
