### ISSUE TITLE
PowerShell 7 Support

### ISSUE THREAD

**Issue by aakash-shah** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#232]
Hello! It appears PowerShell 7 is not supported with the SharePoint PowerShell module. Please clarify on this page that PS v7 is not supported and an ETA as to when PSv7 support will be offered. The error I get when using PSv7 only is:
`Connect-SPOService: Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'`

No errors occur in PSv5, and a web search reveals that this error is related to PSv7/Core not supporting the module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51a2a070-5965-61d1-62e6-433fad2b5ecf
* Version Independent ID: d54bbe0a-37b6-a6f0-0b25-e931ac537d58
* Content: [Get started with the SharePoint Online Management Shell](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online)
* Content Source: [sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md)
* Service: **sharepoint-powershell**
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @aakash-shah 
You can see in this other article (same section) https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/introduction-sharepoint-online-management-shell that it is explained that the module is a Windows PowerShell module (5.1)

> The SharePoint Online Management Shell is a **Windows PowerShell module** that you can use to manage SharePoint settings at the organization level and site collection level. 

When support gets released for this other PS Version the article will be updated to reflect this.

Thank you,
