### ISSUE TITLE
OneDriveLoopSharingCapability missing vital info

### ISSUE THREAD

**Issue by markuspelto** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#234]
Documentation in this doc and in support article (https://support.microsoft.com/en-us/office/enable-microsoft-whiteboard-on-onedrive-for-business-2fae9707-0c9b-42f8-a85f-9628b698ac82) both state:

"If you have the external sharing for ODB allowed, no further action is required. **If you have external sharing disabled, you can leave it disabled** but you must enable this new setting.

Connect to SharePoint Online PowerShell and enable this using the Set-SPOTenant cmdlet.
Set-SPOTenant -OneDriveLoopSharingCapability ExternalUserAndGuestSharing"

Based on testing in multiple customer and partner demo environments, you are unable to run this command unless your tenant is set to allow anonymous sharing in SharePoint tenant level. This is really important information and currently missing in both articles. Most of the companies don´t want to allow anonymous sharing, but they would like to allow temporary Whiteboarding with guests in meetings. This combination doesn´t seem to be possible and therefore the documentation is bit misleading. 

Any change to check with product team, if this behavior is intended and document the extra requirements? Thanks in advance!

**Comment by get-itips** [comment]
Hello @markuspelto 
How are you?
Do you refer to this error message?

`The SharingCapability set for this SPOSite will not take effect until the 'ExternalUserAndGuestSharing'
SharingCapability is also enabled on the SPOTenant.`

Thanks for clarifying

**Comment by markuspelto** [comment]
Hi @get-itips !
Thanks great, how are you?

Yes, that is the one! Full error:

```
WARNING: The SharingCapability set for this SPOSite will not take effect until the 'ExternalUserAndGuestSharing'
SharingCapability is also enabled on the SPOTenant.
Set-SPOTenant : You can’t set the sharing capability to the level you specified, because it is a less restrictive
setting than either its parent site collection or your organization.
At line:1 char:1
+ Set-SPOTenant -OneDriveLoopSharingCapability ExternalUserAndGuestShar ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-SPOTenant], ServerException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.ServerException,Microsoft.Online.SharePoint.PowerShell.SetTe
   nant
```

**Comment by get-itips** [comment]
@markuspelto Markus, thanks, will check if something changed and if necessary a change to the doc

**Comment by markuspelto** [comment]
Hello @get-itips!

I had the same results in my tests. It's just that the requirement to allow anonymous sharing in SPO tenant level is not mentioned anywhere. 

I think it would be helpful to include it, so that you could scrap this idea without going in to testing and then scrap it, because of typical customer compliance requirements.

**Comment by get-itips** [comment]
Hello @markuspelto 
I'll propose to specify that, if it gets approval, it will be in the published version of the article.

**Comment by markuspelto** [comment]
Hello @get-itips
Awesome, big thanks for your help!
