### ISSUE TITLE
Parameter incorrect

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#237]
-InformationSegment is not a valid parameter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70048c8b-cd6e-b20a-b9e4-7e5ed781cc29
* Version Independent ID: 9cfa221c-259a-633d-e176-32ffc17e085e
* Content: [Get-SPOSite (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-sposite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSite.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSite.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@get-itips

**Comment by get-itips** [comment]
Hello @danmyhre Dan, it's true, it is actually a property of the resultant object.

**Comment by danmyhre** [comment]
yes, the result object has a property called InformationSegment, but the cmdlet does not have a parameter call **-InformationSegment**

This is about the **parameter**

Get-SPOSite : A parameter cannot be found that matches parameter name 'InformationSegment'.

**Comment by get-itips** [comment]
@danmyhre Exactly, an edit is already on the way, thanks
