### ISSUE TITLE
suggestion to reword DisableOutlookPSTVersionTrimming parameter description

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#250]
This paragraph discusses the DisableOutlookPSTVersionTrimming in the future-tense, which has had no effect for over 1 year. 

In addition, people coming here to research the issue should be directed to a source that describes how this feature works or that this feature doesn't work, if there is a retention policy applied, which is a very common scenario.

**Comment by yogkumgit** [comment]
@get-itips

**Comment by get-itips** [comment]
Hello @Mike-Crowley Mike, how are you?
Can you please include the link to the article you are talking about? Thanks

**Comment by Mike-Crowley** [comment]
https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/Set-SPOTenant?view=sharepoint-ps#parameters
