### ISSUE TITLE
Description Chapter of the `Get-SPSite` help the Property `SecondaryOwner` should be `SecondaryContact` 

### ISSUE THREAD

**Issue by ChristophHannappel** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#251]
In the Description Chapter of the `Get-SPSite` help the Property `SecondaryOwner` should be `SecondaryContact` 
`Get-SPSite` throws an error when using `SecondaryOwner`

> Get-SPSite : A filter matching SecondaryOwner could not be found. This command accepts the following filters: “Owner”, “SecondaryContact”, or “LockState”.

Current Text
> These site collection properties are Owner, *SecondaryOwner*, and LockState. The Filter parameter is a script block that uses the same syntax as a Where-Object statement, but is run on the server for faster results.

Proposal:

These site collection properties are Owner, SecondaryContact, and LockState. The Filter parameter is a script block that uses the same syntax as a Where-Object statement, but is run on the server for faster results.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d980e9de-c97b-834f-7b1e-1ffb61b8cde2
* Version Independent ID: 88924077-cc80-a620-7a42-5c011974bff1
* Content: [Get-SPSite (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/get-spsite?view=sharepoint-server-ps)
* Content Source: [sharepoint/sharepoint-server-ps/sharepoint-server/Get-SPSite.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-server-ps/sharepoint-server/Get-SPSite.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by yogkumgit** [comment]
@get-itips
