### ISSUE TITLE
Cmdlet not available

### ISSUE THREAD

**Issue by PowershellScripts** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#270]
Is the cmdlet available in the current modules? It doesn't seem to be. Same for 
Set-SPOStructuralNavigationCacheSiteState
Get-SPOStructuralNavigationCacheWebState
Get-SPOStructuralNavigationCacheSiteState

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 459ed4f3-05c3-a5e5-38a3-251d04bba58d
* Version Independent ID: 5210c7b2-6e3f-9321-977b-2dda53c77d48
* Content: [Set-SPOStructuralNavigationCacheWebState (Microsoft.Online.SharePoint.PowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spostructuralnavigationcachewebstate?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOStructuralNavigationCacheWebState.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOStructuralNavigationCacheWebState.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @ParamveerSisodia
* Microsoft Alias: **paramsis**

**Comment by get-itips** [comment]
Hello @PowershellScripts I could find the cmdlets in `16.0.22615.12000`

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @PowershellScripts Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
