### ISSUE TITLE
Missing "Created From" property in Get-SPOSite

### ISSUE THREAD

**Issue by potluri96** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#272]
Hello,

I realized in SharePoint Admin Center there is a field called "Created From" and i am unable to find an equivalent command that will help me output how the site was created. Is that feature not available in the SharePoint PowerShell Module?

<img width="137" alt="Screenshot 2022-06-28 170229" src="https://user-images.githubusercontent.com/66481275/176308153-f2738c9c-09e6-4689-99ab-bc8db73c5ead.png">

**Comment by get-itips** [comment]
Hello @potluri96 
Currently `Get-SPOSite` does not return this information.
Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @potluri96 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
