### ISSUE TITLE
Example 2 - encourages people to put username and password in script

### ISSUE THREAD

**Issue by meta-l** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#275]
Don't think this is a terribly good idea, as it shows that MS recommend in the second example to hardcode admin credentials in a script. Can we remove example 2 and maybe put a recommendation to not hardcode credentials?

**Comment by meta-l** [comment]
Sorry, assumed the comment would link automatically. My fault.

https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/connect-sposervice?view=sharepoint-ps

**Comment by get-itips** [comment]
Hello @meta-l 
How are you?
It is not a recommendation, just a valid example, for other cmdlets that also serve a connection, in the past, people asked for the alternative to specify credentials, I agree with you that I wouldn't prefer to use that, however it is still valid example and some people look for it, for specific purposes.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @meta-l Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
