### ISSUE TITLE
Rename the example 

### ISSUE THREAD

**Issue by jasonwbaxter** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#277]
From :

New-SPPowerPointConversionServiceApplication -Name "MyWorkgroupPPTApp" -ApplicationPool "SharePoint Web Services Default"

To:

New-SPPowerPointConversionServiceApplication -Name "PowerPoint Conversion Service Application" -ApplicationPool "SharePoint Web Services Default"

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b9fd37c-c09b-1d4a-8a6d-3bddd56dd622
* Version Independent ID: 364b076b-332e-66b1-d315-340354a55a5c
* Content: [New-SPPowerPointConversionServiceApplicationProxy (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/new-sppowerpointconversionserviceapplicationproxy?view=sharepoint-server-ps)
* Content Source: [sharepoint/sharepoint-server-ps/sharepoint-server/New-SPPowerPointConversionServiceApplicationProxy.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-server-ps/sharepoint-server/New-SPPowerPointConversionServiceApplicationProxy.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Thanks for your feedback, will edit both the service application and proxy examples.
