### ISSUE TITLE
Get-SPOMalwareFileContent - Expand example to show how to save the file locally

### ISSUE THREAD

**Issue by JaredRic** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#281]
In its current form the documentation for Get-SPOMalwareFileContent shows the following examples:

$file = Get-SPOMalwareFile -FileUri "https://contoso.com/sites/Marketing/Shared Documents/Doc1.docx"
Get-SPOMalwareFileContent -MalwareInfectedFile $file

Running just this gives you the first byte of the stream and nothing else. Please add an example of saving the returned file stream to disk. This might not be the best method, but I had to use the following:

```
$SPOFileUri = "https://contoso.sharepoint.com/sites/test1/Shared%20Documents/malware.txt"

$fileName = $SPOFileUri.split("/")[-1]
$localFolder = ".\$fileName"
$targetfile = New-Object IO.FileStream ($localFolder,[IO.FileMode]::Create)
[byte[]]$readbuffer = New-Object byte[] 1024

$file = Get-SPOMalwareFile -FileUri $SPOFileUri
$responseStream = Get-SPOMalwareFileContent -MalwareInfectedFile $file
do{
    $readlength = $responsestream.Read($readbuffer,0,1024)
    $targetfile.Write($readbuffer,0,$readlength)
}
while ($readlength -ne 0)
$targetfile.close()
```

This saves the file to the current working directory in PowerShell using the original file's name. Even better, maybe update the command to have a local save path for a parameter to avoid the necessary additional work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13642175-04a9-43e8-f7ae-b80afa7f31e0
* Version Independent ID: e43fda5c-f227-9cf3-56c7-b3954460a72c
* Content: [Get-SPOMalwareFileContent (Microsoft.Online.SharePoint.PowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spomalwarefilecontent?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMalwareFileContent.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMalwareFileContent.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @VINANDI
* Microsoft Alias: **vinandi**

**Comment by get-itips** [comment]
Hello @JaredRic I am looking into this.
