### ISSUE TITLE
Is Set-SPOSiteOffice365Group still not GA?

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#282]
Hello, 

As far as I know, Set-SPOSiteOffice365Group has been available since about 2018.
However, the documentation states that it is still a preview and not supported for production use.

I believe the documentation is not fresh as the command works fine. Is this command still in preview now and not supported for use by production tenants?

![image](https://user-images.githubusercontent.com/13634805/183851319-4e938a56-1a19-41a8-b6c2-87d4d99e5e17.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99757b18-0d4e-606b-d0c6-b761a3cf8599
* Version Independent ID: a2bb5cc3-3009-d9a2-78c5-eec63fefabe3
* Content: [Set-SPOSiteOffice365Group (Microsoft.Online.SharePoint.PowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spositeoffice365group?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteOffice365Group.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteOffice365Group.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by yogkumgit** [comment]
@get-itips

**Comment by get-itips** [comment]
@kefujino I am looking into this
