### ISSUE TITLE
SharePoint Module link is wrong/old

### ISSUE THREAD

**Issue by adamjacobsmsft** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#284]
SharePoint module download should link to https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51a2a070-5965-61d1-62e6-433fad2b5ecf
* Version Independent ID: d54bbe0a-37b6-a6f0-0b25-e931ac537d58
* Content: [Get started with the SharePoint Online Management Shell](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online)
* Content Source: [sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md)
* Service: **sharepoint-powershell**
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @adamjacobsmsft 
The link you provided in the issue description is the same as the article you are opening the issue for.
Both link versions to download the SPO Shell are provided.

Can you please specify which link do you think is wrong? Thanks

**Comment by adamjacobsmsft** [comment]
Sorry, I sent the wrong page. This page https://docs.microsoft.com/en-us/microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window?view=o365-worldwide tells you to go to https://go.microsoft.com/fwlink/p/?LinkId=255251 to download SharePoint PowerShell module, but instead it should point to https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online

**Comment by get-itips** [comment]
@adamjacobsmsft Got it, it makes sense as the other modules in the bullet point go to similar pages, however, that article isn't in the repository you opened the issue for (OfficeDocs-SharePoint-PowerShell) I'll open a PR to edit the article in the other repository (microsoft-365-docs), if it is accepted and it gets merged, it will be reflected in the published version of the article.

**Comment by Rajesh-Pradhan** [comment]
IRM Setting status is missing in Get-SPOTenant. Does anyone have any idea?
