### ISSUE TITLE
The examples for connecting to SPO service didn't work, needed to specify the tenant administration site

### ISSUE THREAD

**Issue by JohnMark8080** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#290]
The guidance makes it seem that in my admin role I could connect directly to my site. I needed to specify the tenant admin site, like this:  `Connect-SPOService -Url https://siteNameHere-admin.sharepoint.com` as `Connect-SPOService -Url https://binaryfilter.sharepoint.com` produced an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51a2a070-5965-61d1-62e6-433fad2b5ecf
* Version Independent ID: d54bbe0a-37b6-a6f0-0b25-e931ac537d58
* Content: [Get started with the SharePoint Online Management Shell](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online)
* Content Source: [sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md)
* Service: **sharepoint-powershell**
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @JohnMark8080 Mark,
Every example uses a sample SharePoint Online Administration Center site and not a specific site.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @JohnMark8080 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
