### ISSUE TITLE
-Confirm does not work with Update-SPODataEncryptionPolicy

### ISSUE THREAD

**Issue by ITAndy23** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#292]
Trying to automate `Update-SPODataEncryptionPolicy` when our key changes. 
However, prompt asks "Are you sure you want to perform this action? (Y/N)" .
Adding `-Confirm:$False` does not perform the expected behavior. 
Documentation shows it should work and bypass the prompt. 
This is my line:
`Update-SPODataEncryptionPolicy -KeyVaultName $VaultName -KeyName $KeyName -KeyVersion $KeyVersion -KeyType Primary -Confirm:$False`

Am i using this wrong? If not, documentation needs to be updated or powershell command needs to be fixed.

**Comment by get-itips** [comment]
Hello @ITAndy23 Andy, how are you?
We had reports of the same behavior for other cmdlets in the past, and we try to inform about this to the team so they resolve this.
Thanks for your feedback!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @ITAndy23 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ITAndy23** [comment]
> 

What was the fix for this?
Did the powershell command get fixed or the documentation was corrected/updated?
Thanks

**Comment by yogkumgit** [comment]
@get-itips

**Comment by get-itips** [comment]
Hello @ITAndy23 I managed to report this to the team.
