### ISSUE TITLE
Update -OneDriveLoopSharingCapability to -AllowAnonymousMeetingParticipantsToAccessWhiteboards

### ISSUE THREAD

**Issue by naizatan** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#307]
MC337624 states -OneDriveLoopSharingCapability has been replaced by -AllowAnonymousMeetingParticipantsToAccessWhiteboards. Is it possible to add the latter command/update the page? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da2c76d9-43fd-c631-e6d4-69852b376444
* Version Independent ID: b8ae322e-d3a7-9759-8407-b20f7469cad7
* Content: [Set-SPOTenant (Microsoft.Online.SharePoint.PowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Hello @naizatan 
It seems I cannot access that MC anymore, can you share the text that states that?

I also checked and I see, both parameters in the latest version of Set-SPOTenant.

**Comment by naizatan** [comment]
Sure, here is the content:

> MC337624
> (Updated) Temporary Whiteboard collaboration for external and shared device accounts
> Updated June 17, 2022: As previously stated, Microsoft Whiteboard on OneDrive for Business (ODB) is leveraging a new capability that allows temporary access for external and shared device accounts. This feature is now fully rolled out as of June 14, 2022. Microsoft Whiteboard on OneDrive for Business (ODB) is leveraging a new capability that allows temporary collaboration during a Teams meeting. This applies to device accounts from Surface Hub and Teams Meeting Room devices, as well as any users who are not in your tenant.
> Note: This capability does not enable file-level sharing and does not grant access to the file. It provides temporary access only for the duration of the Teams meeting (similar to PowerPoint Live sharing during a meeting).This message is associated with Microsoft 365 Roadmap ID 66759
> [When this will happen:]
> This feature is now fully rolled out as of June 14, 2022. 
> [How this will affect your organization:]
> For external and shared device accounts to join meetings, Whiteboard relies on a new capability that allows temporary access for these accounts. This applies to device accounts from Surface Hub and Teams Meeting Room devices, as well as any users who are not in your tenant. 
> This capability does not enable file-level sharing and does not grant access to the file. It provides temporary access only for the duration of the Teams meeting (similar to PowerPoint Live sharing during a meeting). 
> [What you need to do to prepare] 
> If you have external sharing enabled for ODB, no further action is required.  
> If you restrict external sharing for ODB, you can keep it restricted and just enable a new setting in order for external and shared device accounts to work. 
> Using PowerShell, connect to your tenant and ensure the SPO module is updated by running the following command:  
> Update-Module -Name Microsoft.Online.SharePoint.PowerShell
> Then run the following command: 
> Set-SPOTenant -AllowAnonymousMeetingParticipantsToAccessWhiteboards On
> **This setting applies only to whiteboards and replaces the previously shared settings, OneDriveLoopSharingCapability and CoreLoopSharingCapability. Those are no longer applicable and can be disregarded.** 
> Note: The Teams meeting setting “Anonymous users can interact with apps in meetings” is enabled by default. If you have disabled it, any anonymous users (as opposed to guests or federated users) will not have access to the whiteboard during the meeting. 

Seems it's also already in Whiteboard docs: https://docs.microsoft.com/en-us/microsoft-365/whiteboard/manage-sharing-organizations?view=o365-worldwide

**Comment by get-itips** [comment]
Thanks @naizatan for adding more information

**Comment by naizatan** [comment]
@get-itips Thank you for the update. But I see that OneDriveLoopSharingCapability is still on the page, with similar descriptions to AllowAnonymousMeetingParticipantsToAccessWhiteboards. Is the former command still somehow applicable? e.g., is there any functionality of the former command that is not covered by the latter?

**Comment by get-itips** [comment]
The parameter is still there in the cmdlet so we need to keep it in the article until it is removed.
