### ISSUE TITLE
IRM Setting status is missing in Get-SPOTenant

### ISSUE THREAD

**Issue by Rajesh-Pradhan** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#311]
IRM Setting status is missing in Get-SPOTenant. Does anyone have any idea?

**Comment by get-itips** [comment]
Hello @Rajesh-Pradhan 
Here, we are limited to documentation issues and fixes, I think your inquiry is best suited for this other resource https://feedbackportal.microsoft.com/feedback/forum/06735c62-321c-ec11-b6e7-0022481f8472

**Comment by yogkumgit** [comment]
@Rajesh-Pradhan Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
