### ISSUE TITLE
SPO management shell does not work on SharePoint Server

### ISSUE THREAD

**Issue by Noddy001** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#317]
Issue /Problem Description: SPO management shell does not work on SharePoint Server

User Affected: All

Business Impact: cannot use SPO management Shell on SharePoint Servers

Troubleshooting: 
-	Ater installing SharePoint Management shell, when we try to import the module it ends up with below error.

Import-Module : Could not load type 'Microsoft.SharePoint.Client.Publishing.PortalLaunch.PortalLaunchRedirectionType'
from assembly 'Microsoft.SharePoint.Client.Publishing, Version=16.0.0.0, Culture=neutral,
PublicKeyToken=71e9bce111e9429c'.
At line:1 char:1
+ Import-Module Microsoft.Online.SharePoint.PowerShell -DisableNameChec ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], TypeLoadException
    + FullyQualifiedErrorId : System.TypeLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand

Cause: 
Since SP2016 server already has the Microsoft.SharePoint.Client.Publishing.dll SPO management shell ends up referring to it and fails to load.

I compared the version of these DLLs from my client machine with the one on SP server and found SP Server dll to be older than what SPO Mgmt requires.

SP Server DLL
Version: 16.0.4303
Location: C:\Windows\Microsoft.NET\assembly\GAC_MSIL\Microsoft.SharePoint.Client.Publishing\v4.0_16.0.0.0__71e9bce111e9429c\Microsoft.SharePoint.Client.Publishing.dll

SP Online Mgmt shell:
Version: 16.0.21909
Location: C:\Program Files\WindowsPowerShell\Modules\Microsoft.Online.SharePoint.PowerShell\16.0.21909.12000\Microsoft.SharePoint.Client.Publishing.dll

Validation: 
-	To validate this further, I renamed the dll on SP on prem (location mentioned above) and then copied the dll from my client machine to the location on the server. That fixed the problem and I do not face the error anymore. I was able to connect to SPO using management shell.

Ask: 
Please update below article with a NOTE to notify our customers to not use/install SPO management shell on their SP Servers.
https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51a2a070-5965-61d1-62e6-433fad2b5ecf
* Version Independent ID: d54bbe0a-37b6-a6f0-0b25-e931ac537d58
* Content: [Get started with the SharePoint Online Management Shell](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?source=docs)
* Content Source: [sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md)
* Service: **sharepoint-powershell**
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @Noddy001 I'll propose to add that to the note. Thanks

**Comment by Noddy001** [comment]
@get-itips - I appreciate you taking out time to check this. Thank you very much.

**Comment by get-itips** [comment]
Closing as the proposal to add this was not approved by reviewers.

**Comment by Noddy001** [comment]
@get-itips - did they give any reason why it cannot be added in article?

**Comment by get-itips** [comment]
Hello @Noddy001 

I found a use case where SPO Mgmt shell is required in an SP Server, which is this https://learn.microsoft.com/en-us/sharepoint/hybrid/configure-server-to-server-authentication#install-online-service-management-tools-and-configure-the-windows-powershell-window

So a note like the one you are proposing would conflict with it. Usually, when this kind of thing happens, we try to report to the team behind SP/SPO, so I'll try to report about this.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @Noddy001 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
