### ISSUE TITLE
Deprecated parameter ?

### ISSUE THREAD

**Issue by altevid** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#321]
Hi
I'm using SharePoint Server 2019 and I think example 1 is not correct, the -ImportTrustCertificate parameter doesn't seem to exist anymore

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb3788dd-d7a4-8d25-4deb-8f47332272c2
* Version Independent ID: 17639ad6-3fda-d412-e6a7-899e2d7733b4
* Content: [Set-SPTrustedServiceTokenIssuer (SharePointServer)](https://learn.microsoft.com/en-us/powershell/module/sharepoint-server/set-sptrustedservicetokenissuer?view=sharepoint-ps&source=docs)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-server/Set-SPTrustedServiceTokenIssuer.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-server/Set-SPTrustedServiceTokenIssuer.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @altevid thanks for your feedback!
