### ISSUE TITLE
Not supported in PowerShell 7

### ISSUE THREAD

**Issue by spg-iwilson** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#343]
[Enter feedback here]
Please add a note to indicate that this only works in Windows PowerShell and not Microsoft PowerShell. The page mentions "using PowerShell 5 or newer" which is confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51a2a070-5965-61d1-62e6-433fad2b5ecf
* Version Independent ID: d54bbe0a-37b6-a6f0-0b25-e931ac537d58
* Content: [Get started with the SharePoint Online Management Shell](https://learn.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online)
* Content Source: [sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Thanks for your feedback

**Comment by neilmca-inc** [comment]
Needs re-opening as. a year later, it's still not clear! Wasted half an hour wondering why the cmdlets weren't working (Pwsh 7.2.14 here)
