### ISSUE TITLE
Invoke-SPOSiteDesign does not provision site columns in an existing list correctly

### ISSUE THREAD

**Issue by marcdayton** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#344]
I created a site design using Get-SPOSiteScriptFromWeb.

Get-SPOSiteScriptFromWeb -WebUrl $sourceUrl -IncludedLists ("Lists/ProjectTasks") -IncludeSiteExternalSharingCapability -IncludeBranding -IncludeTheme

I used Invoke-SPOSiteDesign -Identity 49beec38-1388-4432-893f-00ac4b56c789  -WebUrl $siteCollectionUrl 
to apply the template.

The existing list Project Tasks is provisioned, but the site columns that were added to the list and show up in the item content type on the original site are not in the content type of provisioned list.  
The columns look to be added as local columns (since they are not available in the site columns area on the original site), which matches the provisioned site, but the columns were not added to the item content type of the list so the forms for the list only contain the Title field.
I would like to use this template to stamp out our project sites.  Is this a bug, or am I doing something wrong?  

Any help is appreciated.  Thanks

**Comment by get-itips** [comment]
Hello @marcdayton 
Here, we are limited only to issues in documentation like typos or missing information.
For your inquiry the best would be to open a support request or [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/index.html).

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @marcdayton Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@marcdayton As we are limited to documentation updates, we proceed here to close it. Thanks again for raising this issue.
