### ISSUE TITLE
Start-SPOTenantRename does not start

### ISSUE THREAD

**Issue by RogerInomo** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#345]
SPOTenantRename changes after reaching the ScheduledDateTime from Queued to Suspended (without error) but does not start.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ab64873-7703-065b-85b7-7924262f934a
* Version Independent ID: b06d3565-fa74-bc9b-5f3f-7bf7d238d1b6
* Content: [Start-SPOTenantRename (Microsoft.Online.SharePoint.PowerShell)](https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/start-spotenantrename?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Start-SPOTenantRename.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Start-SPOTenantRename.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @WayneEwington
* Microsoft Alias: **waynewin**

**Comment by WayneEwington** [comment]
Please run the PowerShell cmdlet Get-SPOTenantRenameStatus. If the status is an error or suspended, then please contact Microsoft Support in order for them to investigate.

**Comment by yogkumgit** [comment]
@RogerInomo Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@RogerInomo Thank you. You can initiate the PR any time you have more information about this topic, reviewers can review and approve the PR, if they find it suitable. We proceed to close the issue now.
