### ISSUE TITLE
Missing documentation for OnPrem PnP PowerShell

### ISSUE THREAD

**Issue by lafe** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#346]
The documentation folder for the "old" PnP PowerShell module (https://github.com/pnp/PnP-PowerShell/tree/master/Documentation) states that the documentation for this module has been moved to the Microsoft documentation and points to this site. This site does not have any documentation for that module but points to the documentation of the new module at https://pnp.github.io/powershell/articles/index.html. Unfortunately, some of us have to use the old module due to an old SharePoint environment that has to be supported (in this case: migration). It is very cumbersome that there is no documentation on how to install it or use it and that we have to reengineer everything.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e257652-6b19-287b-7f39-21c2a0909c09
* Version Independent ID: 10c59abb-83b5-1ae4-2008-0a53e9ca952e
* Content: [PnP PowerShell Overview](https://learn.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @lafe I am looking into this

**Comment by get-itips** [comment]
Hello @lafe Lars
I could get this information:

doc for PnP for SP Server cmdlets is still on the Get-Help <pnpcmdletname> in case you want to query them, as for the markdown https://github.com/pnp/PnP-PowerShell/tree/master/Documentation saying that the documentation is now on Docs, is unfortunately out of our scope to correct, but I notified the authors.

Hope this information helps you,

**Comment by lafe** [comment]
Thank you for the feedback. In my opinion, it would be great if this information is mentioned on the page. Currently, there is no acknowledgement that there is a solution for the on Premises environments.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @lafe Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
