### ISSUE TITLE
Parameter ShowOpenInDesktopOptionForSyncedFiles  for Set-SPOTenant not available

### ISSUE THREAD

**Issue by saregbesola** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#352]
1. Is ShowOpenInDesktopOptionForSyncedFiles property removed from the Tenant level config settings? I can't get it whenever I run Get-SPOTenant commandlet, and I can't set a value for it either. 

2. What is the purpose of this setting since we already have "open in app" option in the shortcut menu for a synched file? 

https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps#-showopenindesktopoptionforsyncedfiles

**Comment by get-itips** [comment]
Hello @saregbesola 
How are you?
About question 2, do you mean that you are seeing the Open in App even if ShowOpenInDesktopOptionForSyncedFiles is false?

**Comment by saregbesola** [comment]
@get-itips , yes and I know what purpose ShowOpenInDesktopOptionForSyncedFiles  serves now. The setting only enables open in app option for files that are not office documents e.g., PDF, text file, tiff etc. I will be closing this issue. Thanks
