### ISSUE TITLE
AuthenticationContextName value not being returned

### ISSUE THREAD

**Issue by DavidB1987** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#353]
No values are retuned when executing following PowerShell script:
Connect-SPOService -Url _*value*_
Get-SPOSite -Limit ALL | Where {$_.AuthenticationContextName -like "_*value*_"} 

A workaround throws 'error 429' after going through about 600 sites:
Connect-SPOService No values are retuned when executing following PowerShell script:
Connect-SPOService -Url _*value*_
Get-SPOSite -Limit ALL | Where{$_.AuthenticationContextName -like "_*value*_"} 

A workaround throws 'error 429' after going through about 600 sites:
Connect-SPOService -Url _*value*
$sites = Get-SPOSite -Limit All-Url _*value*
$sites = Get-SPOSite -Limit All

$sites | ForEach-Object{Get-SPOSite $_ | select Url, AuthenticationContextName} 

The following workaround works but takes quite some time:
(with some trial and error I found I had to set the start-sleep at 3 minutes)
Connect-SPOService -Url _*value*_
$sites = Get-SPOSite -Limit All
$number = 500 
$parts = $sites.Length / $number
$parts = [math]::ceiling($parts)
$start = $end = 0
Do{
    $parts -=1
    $end += $number
    $sites[$start..$end] | ForEach-Object{ Get-SPOSite $_ | select Url, AuthenticationContextName } | Export-Csv -Path C:\temp\authenticationcontext.csv -NoTypeInformation -Append  
    Start-Sleep -Seconds 180 #To prevent 'error 429' wait 3 minutes
    $start += $number
}
While($parts -ne 0)

Is it possible to update the module, so a value is returned when the command is used:
Get-SPOSite -Limit ALL | Where {$_.AuthenticationContextName -like "_*value*_"}
It works for all other properties and in a matter of seconds. So why not 'AuthenticationContextName' ?

**Comment by get-itips** [comment]
Hello @DavidB1987  how are you?
Here, we are limited to correct articles and documentation, for example typos, missing or wrong information.
For your inquiry, the best would be this other resource https://feedbackportal.microsoft.com/feedback/forum/06735c62-321c-ec11-b6e7-0022481f8472
