### ISSUE TITLE
Being able to create shortcuts between different site libraries

### ISSUE THREAD

**Issue by arielpont** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#354]
By not being able to create direct access between libraries, the work becomes more complicated. For example, my organization is organized by areas and projects. The "Marketing" area needs to be able to add shortcuts to the folder where the project is located. The project is in the hands of another "Development" group. So far the only way is to create a link to the file using the share link. It is very impractical. At the same time, generating a copy of the documents is not a possibility because it becomes messy, there may be different outdated versions of the same file and it takes up more space.

If the shortcuts could be created between libraries and not only in "My files" it will help a lot to have more possibilities to organize better.

**Comment by get-itips** [comment]
Hello @arielpont Ariel, how are you?
Here, we are limited to correct articles and documentation, for example typos, missing or wrong information.
For your inquiry, the best would be this other resource https://feedbackportal.microsoft.com/feedback/forum/06735c62-321c-ec11-b6e7-0022481f8472
