### ISSUE TITLE
Need details of provisioning timer job

### ISSUE THREAD

**Issue by jmuehlenbein** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#364]
Hello, can you please, please add more detail on the timer job which does the actual OneDrive provisioning? How long might it take to provision?  We are scripting onboarding and need to configure the OneDrive of the new user but presumably the OneDrive needs to exist before we can configure it. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e37f6a5c-b620-229d-a0dc-289960c6806c
* Version Independent ID: 71d9f7bc-6ef3-8fd6-bb7f-236a902bce2a
* Content: [Request-SPOPersonalSite (Microsoft.Online.SharePoint.PowerShell)](https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/request-spopersonalsite?view=sharepoint-ps&preserve-view=true)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Request-SPOPersonalSite.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Request-SPOPersonalSite.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Hello @jmuehlenbein 
How are you? 

I would recommend checking if the requested personal site exists to continue your configuration, timer jobs runs vary so it is not an exact thing that can be documented, unfortunately.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @jmuehlenbein Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
