### ISSUE TITLE
Documentation should reflect the OS versions that the command lets are compatible with

### ISSUE THREAD

**Issue by loaderladdy** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#366]
Like many PowerShell Core users I’ve spent many a fruitless hour trying to understand why Microsoft.SharePoint.Online.PowerShell module does not work on non-Windows OSes. One of your colleagues pointed out that this PowerShell module has a dependency on .NET Framework 4.x which is only compatible with Windows.

I think that the documentation for PowerShell modules should reflect which OSes a module is compatible with.  It would save the module user a lot of time if this information was available to them within each module’s documentation.

I hope you can consider this enhancement request to your product documentation.

kind regards,

Pete

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d3c1e49-2acd-707a-33b2-2abe705fa123
* Version Independent ID: a6afec72-10c8-84c9-9435-74602c30a3c0
* Content: [Connect-SPOService (Microsoft.Online.SharePoint.PowerShell)](https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/connect-sposervice?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Hello @loaderladdy 
Many thanks for your feedback!
That is documented in the index file for the module description here

https://learn.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/introduction-sharepoint-online-management-shell?view=sharepoint-ps

where it says it is a Windows PowerShell (not core/7) module.

Hope this information helps you,

**Comment by loaderladdy** [comment]
Hi @get-itips I could not find the reference on that link, but I might not be understanding what the "index file" is.  I did find it via the link in the first para of the page here [https://learn.microsoft.com/en-us/microsoft-365/enterprise/why-you-need-to-use-microsoft-365-powershell?view=o365-worldwide](url) where it states

> 
![image](https://user-images.githubusercontent.com/15855352/211633460-98023aa5-ca0b-4c2c-b277-24531d4b0583.png)

Am I looking in the wrong place Andreas?

**Comment by get-itips** [comment]
Here in the article I linked

>The SharePoint Online Management Shell is a **Windows PowerShell** module that you can use to manage SharePoint settings at the organization level and site collection level. Command-line operations in **Windows PowerShell** are composed of a series of commands. Each command uses a cmdlet and a set of settings known as parameters. For example, you use the New-SPOSite cmdlet to create a new site collection with a specified title, URL, owner, storage quota, and template (the parameters).

**Comment by loaderladdy** [comment]
I was being thick! I was searching for text that said "core" and couldn't find it. I took your explanation literally.  Of course what you meant was Windows PowerShell means precisely that and by inference excludes the other PowerShell products PowerShell Core and PowerShell 7.  And that was the point I was making in the case that a casual PowerShell user does not make the distinction that Windows PowerShell excludes Core and 7. I know it probably seems daft because the article explicitly says _**Windows**_ PowerShell and the author expects the reader to understand that implicitly but on occasions, especially in technical support documentation it might be more prudent to assume the reader has limited understanding and spell out the constraints so there is no room left for doubt because the author has removed all doubt. Is that fair?

**Comment by get-itips** [comment]
I'll ask the Docs team what they think about this addition and get back, however, I think we don't tend to add those kinds of notes stating what _is not_ supported but what **is** supported.

**Comment by loaderladdy** [comment]
I'd suggest that it included as a system requirement for using PowerShell modules that have Windows dependencies because this explicitly excludes PowerShell version that work on Linux and MacOS, and if it is well worded you'd not have to mention the other OSes.

Mind you, does PowerShell Core and 7 work with SharePoint.Online.PowerShell? Because that would serve to confuse everyone if those PowerShell versions do on Windows but not on Linux or MacOS. 

Hopefully Microsoft are working to retire Windows PowerShell in the near future so there isn't any confusion and Microsoft's SaaS products can be managed from any OS platform

Thanks again

**Comment by yogkumgit** [comment]
@get-itips

**Comment by yogkumgit** [comment]
@get-itips Kindly advise.

**Comment by get-itips** [comment]
@yogkumgit Asked internally and I received the feedback to leave it as-is, only adding a link to Windows PowerShell requirements.

**Comment by loaderladdy** [comment]
Thank you for taking this forward Andres 👍

**Comment by loaderladdy** [comment]
Consider the matter closed

**Comment by get-itips** [comment]
> Thank you for taking this forward Andres 👍

thanks for returning and sharing feedback, that improves articles.
