### ISSUE TITLE
SharePoint Site permissions for Partner Delegated admins using Set-SPOUser

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#369]
Please provide example how we can add Partner support , to the SharePoint Online Site, using powershell.

This was possible in classic SharePoint Online admin center.

Also reference - https://worktogether.tech/2017/05/13/give-a-partner-access-to-your-spo-site/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86839720-1641-7151-f329-09577c18efae
* Version Independent ID: b6ea24ce-f4b4-f2a3-5a54-f8b88d429788
* Content: [Set-SPOUser (Microsoft.Online.SharePoint.PowerShell)](https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/set-spouser?view=sharepoint-ps&preserve-view=true)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOUser.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOUser.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by hkusulja** [comment]
Referring also #3568

**Comment by get-itips** [comment]
Hello @hkusulja 

Do you mean something like this?

`Set-SPOUser -Site https://m365x967470.sharepoint.com/sites/appcatalog -LoginName "i:0#.f|membership|admin_m365x47406.onmicrosoft.com#ext#@m365x967470.onmicrosoft.com" -IsSiteCollectionAdmin $true`

Following the instructions

```
Add Support Partner

This option is available in PowerShell only. Go to the Site Permissions page for a site where you've added the support partner. Copy the encoded string for the partner, and to add it to other sites, use the PowerShell cmdlet Set-SPOUser.
```

**Comment by hkusulja** [comment]
oh, ok, maybe, if it works. Please document also, if this example login name and how to find it for partner tenant?
Also, please state does this work with Partner Delegated Admin rights, and new Granular Partner Delegated Admin rights (GDAP)

**Comment by get-itips** [comment]
> oh, ok, maybe, if it works. Please document also, if this example login name and how to find it for partner tenant?

What I did was follow the current instructions found at https://learn.microsoft.com/en-US/sharepoint/site-collections-page

> Also, please state does this work with Partner Delegated Admin rights, and new Granular Partner Delegated Admin rights (GDAP)

It seems that for GDAP the process is different https://learn.microsoft.com/en-us/partner-center/gdap-supported-workloads#sharepoint

For that case, the best would be to open a Partner support case to confirm if you can use this cmdlet.

**Comment by hkusulja** [comment]
> > oh, ok, maybe, if it works. Please document also, if this example login name and how to find it for partner tenant?
> 
> What I did was follow the current instructions found at https://learn.microsoft.com/en-US/sharepoint/site-collections-page
> 

Mentioned page just links to this one.

> > Also, please state does this work with Partner Delegated Admin rights, and new Granular Partner Delegated Admin rights (GDAP)
> 
> It seems that for GDAP the process is different https://learn.microsoft.com/en-us/partner-center/gdap-supported-workloads#sharepoint
> 
> For that case, the best would be to open a Partner support case to confirm if you can use this cmdlet.

The support team uses the same public documentation, and since this page is not clear, then please update it, how to use GDAP also.

Still pending to update page - https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/set-spouser?view=sharepoint-ps&preserve-view=true
with full information and example to obtain partner username and example to add it as a support partner

Thank you in advance

**Comment by yogkumgit** [comment]
@get-itips

**Comment by yogkumgit** [comment]
@get-itips Please reply the comment posted in the PR. Thanks

**Comment by yogkumgit** [comment]
@hkusulja checking with author internally. Thanks

**Comment by get-itips** [comment]
Hello @hkusulja 
We asked internally and the answer is that it is not supported to use the cmdlet for GDAP.

**Comment by hkusulja** [comment]
> Hello @hkusulja We asked internally, and the answer is that it is not supported to use the cmdlet for GDAP.

can you document this in official documentation that this is not supported
also meaning, that turning off DAP (in next few weeks), this command is also deprecated then, and this feature does not exists anymore...

**Comment by hkusulja** [comment]
Please document publicly that GDAP is not supported for this command

**Comment by yogkumgit** [comment]
@hkusulja We will recheck with PM and follow the instructions proposed  by experts. Thanks for your quick revert.

**Comment by hkusulja** [comment]
Why documentation can not have information about what behavior is by design.

**Comment by yogkumgit** [comment]
@tiburd For your action please. Thanks

**Comment by tiburd** [comment]
I sent email to senior PM.

**Comment by yogkumgit** [comment]
@tiburd

**Comment by tiburd** [comment]
@get-itips 
Hi Andres,

Please create a PR to add a note that the cmdlet isn't supported for use with GDAP.

Thank you.
