### ISSUE TITLE
Incorrect App Catalog Site template ID

### ISSUE THREAD

**Issue by Guardie** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#375]
The app catalog template name is incorrect.
This should be "APPCATALOG#0", "APCATALOG#0" is mentioned at the SkipWebTemplateChecking parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 60149bc0-c8ca-eb8d-cdae-46515c0d6aa2
* Version Independent ID: feee60e3-507d-2837-8cbb-d2cfd26f9541
* Content: [Update-SPAppCatalogConfiguration (sharepoint-server)](https://learn.microsoft.com/en-us/powershell/module/sharepoint-server/update-spappcatalogconfiguration?view=sharepoint-server-ps)
* Content Source: [sharepoint/sharepoint-server-ps/sharepoint-server/Update-SPAppCatalogConfiguration.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-server-ps/sharepoint-server/Update-SPAppCatalogConfiguration.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Thanks for your feedback
