### ISSUE TITLE
Missing Command Property?

### ISSUE THREAD

**Issue by mattderosia** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#378]
There is supposed to be a property of -VivaConnectionsDefaultStart $true/$false for the Set-SpoHomeSite command, but I am getting the following error:

PS C:\> Set-SPOHomeSite -HomeSiteUrl <home site url> -VivaConnectionsDefaultStart $true
Set-SPOHomeSite : A parameter cannot be found that matches parameter name 'VivaConnectionsDefaultStart'.
At line:1 char:70
+ ... :<home site url> -VivaConnectionsDefaultStart $true
+                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-SPOHomeSite], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Online.SharePoint.PowerShell.SPOHomeSite+SetHomeSite

I have updated to the most recent module version:
PS C:\> Get-InstalledModule Microsoft.Online.SharePoint.PowerShell | FL

Name                       : Microsoft.Online.SharePoint.PowerShell
Version                    : 16.0.23311.12000
Type                       : Module
Description                : Microsoft SharePoint Online Services Module for Windows PowerShell
Author                     : Microsoft Corporation
CompanyName                : MicrosoftSharePoint
Copyright                  : (c) Microsoft Corporation. All rights reserved.
PublishedDate              : 1/27/2023 10:49:41 AM
InstalledDate              : 10/5/2022 12:22:34 PM
UpdatedDate                : 2/2/2023 12:49:02 PM
LicenseUri                 : https://raw.githubusercontent.com/Azure/azure-powershell/preview/LICENSE.txt
ProjectUri                 : https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/introduction-sharepoint-online-management-shell?view=sharepoint-ps
IconUri                    : https://raw.githubusercontent.com/SharePoint/sp-dev-docs/master/docs/images/sp-logo.png
Tags                       : {Office365, SharePoint, SharePointOnline, SPO...}
Includes                   : {Function, RoleCapability, Command, DscResource...}
PowerShellGetFormatVersion :
ReleaseNotes               :
Dependencies               : {}
RepositorySourceLocation   : https://www.powershellgallery.com/api/v2
Repository                 : PSGallery
PackageManagementProvider  : NuGet

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6cc11f65-9afc-7539-deb4-47454b1f6adf
* Version Independent ID: 7ea613d4-7700-e848-c606-d154f72f40a5
* Content: [Set-SPOHomeSite (Microsoft.Online.SharePoint.PowerShell)](https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/set-spohomesite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOHomeSite.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOHomeSite.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @mattderosia 
I do see the parameter in that module version.

**Comment by mattderosia** [comment]
Yes, that might be my next try. I was trying to follow Microsoft's documentation, however, its not included in their SPO module as their documentation indicates.

**Comment by get-itips** [comment]
@mattderosia But I could use the parameter in the cmdlet.

**Comment by mattderosia** [comment]
I agree, it is working now. My apologies.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @mattderosia Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
