### ISSUE TITLE
URL Requirements Not Defined

### ISSUE THREAD

**Issue by jrg-jeff** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#381]
The Set-SPOHomeSite cmdlet has restrictions on the URLs that can be used; however, those restrictions are not defined anywhere.  These restrictions can prohibit the use of sites within the same tenant as a home site, but Microsoft doesn't define what they are.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6cc11f65-9afc-7539-deb4-47454b1f6adf
* Version Independent ID: 7ea613d4-7700-e848-c606-d154f72f40a5
* Content: [Set-SPOHomeSite (Microsoft.Online.SharePoint.PowerShell)](https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/set-spohomesite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOHomeSite.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOHomeSite.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
@jrg-jeff The requirements are mentioned in the linked article https://learn.microsoft.com/en-us/SharePoint/home-site and it says it must be a communication site.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @jrg-jeff Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
