### ISSUE TITLE
How to use the cmd, please provide more complete sample

### ISSUE THREAD

**Issue by Emmanuel30** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#388]
Hi
The examples given for cmdlets never give the **complete** example of cmdlet usage : how to include libraries, how to launch the Powershell window, in which context the cmdlet can be used, etc. the example simply can't work alone. Therefore it is useless for me.

The problem with Microsoft technologies is that it is always somewhere between dev and power users. I used to be a dev long time ago, but I don't do anymore tech now, and it is really time-consuming to always wonder how to use tools just for questions of syntax and context.

Please provide complete example, meaning the full procedure to use the command. And not only a sample line that doesn't work alone.

I have open a Powershell window, I have an account which is admin on my SP Online site, but I need more info than just copying the cmdlet line syntax in this window.

Thank you

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6dfa9cd7-3523-25ae-5d5e-f2159352c590
* Version Independent ID: fdd7374f-3df5-5afa-d9c7-60919329fb75
* Content: [Set-SPUser (sharepoint-server)](https://learn.microsoft.com/en-us/powershell/module/sharepoint-server/set-spuser?view=sharepoint-server-ps)
* Content Source: [sharepoint/sharepoint-server-ps/sharepoint-server/Set-SPUser.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-server-ps/sharepoint-server/Set-SPUser.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @Emmanuel30 

You mentioned SP Online however Set-SPUser is for SharePoint Server/Subscription edition, as the article informs.

Is your feedback intended instead for Set-SPOUser?

Thanks

**Comment by Emmanuel30** [comment]
Hello

For both. No matter which command articles are about, it is always difficult to understand how to use the sample, because of all the prerequisites, the context, things to install or configure before you can use the command.

I use both on prem and online versions of SharePoint.

Thanks

Emmanuel
________________________________
From: Andres Mariano Gorzelany ***@***.***>
Sent: Friday, February 24, 2023 5:07 PM
To: MicrosoftDocs/OfficeDocs-SharePoint-PowerShell ***@***.***>
Cc: Emmanuel Lepessec ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell] How to use the cmd, please provide more complete sample (Issue #388)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hello @Emmanuel30<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEmmanuel30&data=05%7C01%7CELEPESSEC%40cegid.com%7C3fe062f8f12444d7966a08db168147c9%7C604e5547f49c44818476c14f22fd79cb%7C0%7C0%7C638128516751344684%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8Z47pPz7SVDjRtI1oDybKtr8zl5SJMYiorN4pxf%2Bjrk%3D&reserved=0>

You mentioned SP Online however Set-SPUser is for SharePoint Server/Subscription edition, as the article informs.

Is your feedback intended instead for Set-SPOUser?

Thanks

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SharePoint-PowerShell%2Fissues%2F388%23issuecomment-1443913755&data=05%7C01%7CELEPESSEC%40cegid.com%7C3fe062f8f12444d7966a08db168147c9%7C604e5547f49c44818476c14f22fd79cb%7C0%7C0%7C638128516751344684%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=krChzagNP2JxUFbcctNQtJi9jUFJHRXw0ubYZL3lO1o%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEICCLBUAUP3N44L6Q4ZY4TWZDMFLANCNFSM6AAAAAAU4WDMFQ&data=05%7C01%7CELEPESSEC%40cegid.com%7C3fe062f8f12444d7966a08db168147c9%7C604e5547f49c44818476c14f22fd79cb%7C0%7C0%7C638128516751344684%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vv4AP86CNBx5dLAPRaQTsq9%2FaGXRFHY5eamkg6rnfpY%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>


Cegid est susceptible d’effectuer un traitement sur vos données personnelles à des fins de gestion de notre relation commerciale. Pour plus d’information, consultez https://www.cegid.com/fr/privacy-policy
Ce message et les pièces jointes sont confidentiels et établis à l'attention exclusive de ses destinataires. Toute utilisation ou diffusion, même partielle, non autorisée est interdite. Tout message électronique est susceptible d'altération; Cegid décline donc toute responsabilité au titre de ce message. Si vous n'êtes pas le destinataire de ce message, merci de le détruire et d'avertir l'expéditeur.

Cegid may process your personal data for the purpose of our business relationship management. For more information, please visit our website https://www.cegid.com/en/privacy-policy
This message and any attachments are confidential and intended solely for the addressees. Any unauthorized use or disclosure, either whole or partial is prohibited. E-mails are susceptible to alteration; Cegid shall therefore not be liable for the content of this message. If you are not the intended recipient of this message, please delete it and notify the sender.

**Comment by yogkumgit** [comment]
@get-itips

**Comment by get-itips** [comment]
> how to launch the Powershell window

> For both. No matter which command articles are about, it is always difficult to understand how to use the sample, because of all the prerequisites, the context, things to install or configure before you can use the command.

You can find information about how to run this and any cmdlet in the index for the section, for example

https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets?view=sharepoint-server-ps

https://learn.microsoft.com/powershell/sharepoint/sharepoint-online/introduction-sharepoint-online-management-shell?view=sharepoint-ps

**Comment by yogkumgit** [comment]
@Emmanuel30 hope this helps, Thanks
