### ISSUE TITLE
Please add option -DisableBackToClassic as mentioned by MC251565

### ISSUE THREAD

**Issue by JoergWu** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#390]
Please add the missing option to the documentation:

MC251565 – (Updated) New PowerShell to enable or disable the link to return to classic SharePoint

Updated April 23, 2021: We have updated this post with additional details for clarity.  Thank you for your feedback.

On modern SharePoint list and library pages, there's a link in the lower left of the page that says "Return to classic SharePoint."  This link reverts the current list or library back to classic mode.  On the classic page, there's a corresponding link that says, "Exit classic experience."  Tenant administrators can now control whether these links appear.  By default, these links are shown on all list and library pages to all users. 

To remove the links, run the following PowerShell cmdlet:

-  **Set_SPOTenant -DisableBackToClassic $true**

To show these links again, run the following PowerShell cmdlet:

- **Set_SPOTenant -DisableBackToClassic $false**

When this will happen?

The Set-SPOTenant command will be updated in this month’s PowerShell update to contain ‘DisableBackToClassic’ parameter.
Targeted Release environments can start utilizing this in late April and this gradually available to all standard release environments by the end of May.

Source: https://techcommunity.microsoft.com/t5/public-sector-blog/may-2021-microsoft-365-us-public-sector-roadmap-newsletter/ba-p/2350223
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: da2c76d9-43fd-c631-e6d4-69852b376444
* Version Independent ID: b8ae322e-d3a7-9759-8407-b20f7469cad7
* Content: [Set-SPOTenant (Microsoft.Online.SharePoint.PowerShell)](https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Thanks for your feedback!
