### ISSUE TITLE
The commands here do not work on a Mac

### ISSUE THREAD

**Issue by pvolve** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#399]
First off, seriously? You sell Microsoft 365 to small businesses and expect them to be able to do Powershell?

Anyway, following the instructions on this page does not work for Mac. The Microsoft.Online.SharePoint.PowerShell module is installed but when you issue the Connect-SPOService -Url command, you receive:

Connect-SPOService: The term 'Connect-SPOService' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

I have attached a screenshot for reference

![PowerShell Sharepoint Module Installed but command not found](https://user-images.githubusercontent.com/42646492/221375337-a3654c64-2fb8-4e17-95e0-e6c2a5a155c2.png)

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @pvolve Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by SimonSimCity** [comment]
Just for others also running in here ... When you install a module, you have to import it before you can use any of its commands `Import-Module -name Microsoft.Online.SharePoint.PowerShell`
