### ISSUE TITLE
Unknown command

### ISSUE THREAD

**Issue by Karr** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#411]
The EXAMPLE Code has an unknown command:  Get-SPTrustedIdentityProvider
I think maybe it was suppost to be:  Get-SPTrustedIdentityTokenIssuer
Please have this verified.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0ae1638-e6ee-9381-91ae-aaced3a066ae
* Version Independent ID: ba26474f-75c5-cf30-b056-57ecc42cfb5d
* Content: [Add-SPClaimTypeMapping (sharepoint-server)](https://learn.microsoft.com/en-us/powershell/module/sharepoint-server/add-spclaimtypemapping?view=sharepoint-server-ps)
* Content Source: [sharepoint/sharepoint-server-ps/sharepoint-server/Add-SPClaimTypeMapping.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-server-ps/sharepoint-server/Add-SPClaimTypeMapping.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @Karr 
Thanks for your feedback!
