### ISSUE TITLE
PowerShell 7 Support

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#427]
Still no details on powershell 7 support.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7eb69f85-4d46-5c34-c1d5-ce8477fd2080
* Version Independent ID: 3d67d725-4b26-0be2-8071-52e38d18f5f2
* Content: [Intro to SharePoint Online Management Shell](https://learn.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/introduction-sharepoint-online-management-shell?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/sharepoint-online/introduction-sharepoint-online-management-shell.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/docs-conceptual/sharepoint-online/introduction-sharepoint-online-management-shell.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
@danmyhre Hello Dan, at the moment Windows PowerShell is the required and compatible version.
