### ISSUE TITLE
Template Hiding/Unhiding Errors

### ISSUE THREAD

**Issue by AnnaAmelia** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#451]
After following the steps outlined in the article to hide all templates using the command "Set-SPOBuiltInSiteTemplateSettings -Identity '00000000-0000-0000-0000-000000000000' -IsHidden $true," I attempted to make only the Team site template (6b96e7b1-035f-430b-92ca-31511c51ca72) visible again. However, I received an error message stating that this is not a valid site template ID and to obtain the correct ID from https://go.microsoft.com/fwlink/?linkid=2169454 and try again.

Additionally, when trying to hide individual templates by listing their IDs one by one, I encountered issues. I found that the following template IDs could not be hidden:

665da395-e0f9-4c92-b35c-773d8c292f2d
9f21161-0892-497a-91cb-5783eeb1f5f2
665da395-e0f9-4c92-b35c-773d8c292f2d
For these template IDs, I received an error message stating that the site template could not be disabled.

Are there some dependencies and temaplted needs to be hidden in certain order? Why aftre hiding all templates, template ID 6b96e7b1-035f-430b-92ca-31511c51ca72/Team collaboration cannot be set from hidden to visible?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 10e0be42-e202-0561-6166-6ad30af78676
* Version Independent ID: 09b8332a-3360-cf98-6fa5-d7a7d15bb097
* Content: [Set-SPOBuiltInSiteTemplateSettings (Microsoft.Online.SharePoint.PowerShell)](https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/set-spobuiltinsitetemplatesettings?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOBuiltInSiteTemplateSettings.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOBuiltInSiteTemplateSettings.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by AnnaAmelia** [comment]
Hi @yogkumgit  can teh article be updates? My customer managed to solve the problem with Support assistance, the correct ID for Teams collaboration is listed here: https://social.technet.microsoft.com/wiki/contents/articles/54455.power-automate-fetch-site-template-ids.aspx

**Comment by yogkumgit** [comment]
@get-itips

**Comment by get-itips** [comment]
Thanks for your feedback

**Comment by Holland-ODSP** [comment]
@MattEEvans
