### ISSUE TITLE
Seems like the link for the Locale ID's is wrong?

### ISSUE THREAD

**Issue by SimplitizeClaus** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#456]
I think this link is wrong: For more information, see Locale IDs Assigned by Microsoft (https://go.microsoft.com/fwlink/p/?LinkId=242911). 

Could not find any info about the Locale ID's in the linked page

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cbfbe213-47b7-f653-c8de-77aef5d2c959
* Version Independent ID: 171e4cb3-5d5e-80bf-c2e2-df4adf1eaaeb
* Content: [New-SPOSite (Microsoft.Online.SharePoint.PowerShell)](https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/new-sposite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/New-SPOSite.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/New-SPOSite.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Hello @SimplitizeClaus 
How are you?
Thanks for your feedback.
On the linked page, the Locale IDs are in HEX, for example 

English | United States | 0x0409

is 1033 converted to Decimal
