### ISSUE TITLE
Missing information regarding usage for updating trusted identity issuer / certificates

### ISSUE THREAD

**Issue by a-goo** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#477]
If a SAML certificate for SharePoint trust expires and needs to be updated, what's the procedure? 

Do you have to first remove the original trusted identity issuer (_Remove-SPTrustedIdentityTokenIssuer_) or can you just run _Set-SPTrustedIdentityTokenIssuer_ to update? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 305893f9-53cf-3088-cd4c-63471433c260
* Version Independent ID: 3eed3a68-3629-1556-37f5-cdf9948312a3
* Content: [Set-SPTrustedIdentityTokenIssuer (sharepoint-server)](https://learn.microsoft.com/en-us/powershell/module/sharepoint-server/set-sptrustedidentitytokenissuer?view=sharepoint-server-ps&source=recommendations)
* Content Source: [sharepoint/sharepoint-server-ps/sharepoint-server/Set-SPTrustedIdentityTokenIssuer.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-server-ps/sharepoint-server/Set-SPTrustedIdentityTokenIssuer.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @a-goo 
It's been a while since I did this however, the Set- cmdlet is provided to set it so you should able to modify the properties of the SPTrustedIdentityTokenIssuer without removing it first.

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @a-goo Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by a-goo** [comment]
Hi. I need to reopen this to get further clarification.

According to the MS page here https://learn.microsoft.com/en-us/azure/active-directory/saas-apps/sharepoint-on-premises-tutorial one should run the following PowerShell script against the on-prem SharePoint environment for to configure AAD authentication trust & certificate installation:

`# Path to the public key of the Azure AD SAML signing certificate (self-signed), downloaded from the Enterprise application in the Azure portal
$signingCert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2("C:\_install\SharePoint+on-premises.cer")
# Unique realm (corresponds to the "Identifier (Entity ID)" in the Azure AD Enterprise application)
$realm = "urn:sharepoint:federation"
# Login URL copied from the Azure AD enterprise application. Make sure to replace "saml2" with "wsfed" at the end of the URL:
$loginUrl = https://login.microsoftonline.com/86xxxx36-xxxx-xxxx-xxxx-ed1xxxx5f45a/wsfed
 
# Define the claim types used for the authorization
$userIdentifier = New-SPClaimTypeMapping -IncomingClaimType http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name -IncomingClaimTypeDisplayName "name" -LocalClaimType http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn
$role = New-SPClaimTypeMapping http://schemas.microsoft.com/ws/2008/06/identity/claims/role -IncomingClaimTypeDisplayName "Role" -SameAsIncoming
	 
# Let SharePoint trust the Azure AD signing certificate
New-SPTrustedRootAuthority -Name "Azure AD signing certificate" -Certificate $signingCert
	 
# Create a new SPTrustedIdentityTokenIssuer in SharePoint
$trust = New-SPTrustedIdentityTokenIssuer -Name "AzureADTrust" -Description "Azure AD" -Realm $realm -ImportTrustCertificate $signingCert -ClaimsMappings $userIdentifier, $role -SignInUrl $loginUrl -IdentifierClaim $userIdentifier.InputClaimType `


The result output of this can be obtained from PowerShell:

`PS C:\Users\serviceaccount> Get-SPTrustedIdentityTokenIssuer
 
UseStateToRedirect            : False
ProviderUri                   : https://login.microsoftonline.com/86xxxx36-xxxx-xxxx-xxxx-ed1xxxx5f45a/wsfed
ProviderSignOutUri            : 
DefaultProviderRealm          : urn:sharepoint:federation
ProviderRealms                : {}
ClaimTypes                    : {http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name, http://schemas.microsoft.com/ws/2008/06/identity/claims/role}
HasClaimTypeInformation       : True
ClaimTypeInformation          : {name, Role}
ClaimProviderName             : 
UseWReplyParameter            : False
UseWHomeRealmParameter        : False
GroupClaimType                : 
RegisteredIssuerName          : 
DefaultClientIdentifier       : 
ScopedClientIdentifier        : 
AuthorizationEndPointUri      : 
TrustedLoginMethod            : None
ResponseTypesSupported        : 
Scope                         : 
IdentityClaimTypeInformation  : Microsoft.SharePoint.Administration.Claims.SPTrustedClaimTypeInformation
Description                   : Azure AD
SigningCertificate            : [Subject]
                                  CN=Microsoft Azure Federated SSO Certificate
                                
                                [Issuer]
                                  CN=Microsoft Azure Federated SSO Certificate
                                
                                [Serial Number]
                                  59DFD6C0DXXXXXXXXXX5679E7F3D26A0
                                
                                [Not Before]
                                  2023-06-22 09:58:53
                                
                                [Not After]
                                  2026-06-22 09:58:53
                                
                                [Thumbprint]
                                  C575077CAXXXXXXXXXXXXXXXDF42CCC3DCE514A6
                                
AdditionalSigningCertificates : {}
MetadataEndPoint              : 
IsAutomaticallyUpdated        : False
Name                          : AzureADTrust
TypeName                      : Microsoft.SharePoint.Administration.Claims.SPTrustedLoginProvider
DisplayName                   : AzureADTrust
Id                            : 8a8ccab0-XXXX-XXXX-XXXX-4996XXXcb67b
Status                        : Online
Parent                        : SPSecurityTokenServiceManager Name=SecurityTokenServiceManager
Version                       : 1338703
DeploymentLocked              : False
Properties                    : {}
Farm                          : SPFarm Name=SPSE_Config
UpgradedPersistedProperties   : {} `

We now need to update the certificate as we have made changes to the AAD authenticator app and login attempts fail with certificate errors:
![image](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/assets/105272899/14f2698a-de53-43e6-b78f-ee5eb4035d9c)

However, information about updating the certificate is unclear, as the page here does not provide any information about what applies in a scenario for only updating certificates: https://learn.microsoft.com/en-us/powershell/module/sharepoint-server/set -sptrustedidentitytokenissuer?view=sharepoint-server-ps&source=recommendations
 
Looking back at https://learn.microsoft.com/en-us/powershell/module/sharepoint-server/set-sptrustedidentitytokenissuer?view=sharepoint-server-ps&source=recommendations and requirements for the command, the following parameters are mandatory:
-Identity <GUID>
-ImportTrustCertificate <path>
-MetadataEndPoint <URI>
 
Please note that in the result output above "MetadataEndPoint" is without value.

When trying to run PowerShell to update the certificate, we ran the following:
`Set-SPTrustedIdentityTokenIssuer -Identity "8a8ccab0-XXXX-XXXX-XXXX-4996XXXcb67b" -ImportTrustCertificate "C:\_install\Azure AD Trust\Authentication proxy - Kvalitetsledningssystem UAT.cer" -MetadataEndPoint ""`

Which failed with the following error:

`PS C:\Users\serviceaccount> C:\_install\Azure AD Trust\SPserver-Update-SPTrustedIdentityTokenIssuer-WithNewCert.ps1
 
Set-SPTrustedIdentityTokenIssuer : Parameter set cannot be resolved using the specified named parameters.
At C:\_install\Azure AD Trust\SPserver-Update-SPTrustedIdentityTokenIssuer-WithNewCert.ps1:1 char:1
+ Set-SPTrustedIdentityTokenIssuer -Identity "8a8ccab0-xxxx-xxxx-xxxx-4 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-SPTrustedIdentityTokenIssuer], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.SharePoint.PowerShell.SPCmdletSetSPIdentityProvider 
`

**So, for clarification**
1. Based on the login error (screenshot) which indicates a certificate mismatch, is this the correct approach to update the cert? (certs must be updated eventually as they have a limited lifespan)
2. If the error for the last PowerShell script is due to a missing value for the MetadataEndPoint, what is the required value when it is not included in the output?

**Comment by get-itips** [comment]
Hello @a-goo 
You specified MetadataEndPoint and ImportTrustCertificate in the cmdlet run, however those parameters are from different parameter sets, so you either use ImportTrustCertificate or MetadataEndPoint

**Comment by a-goo** [comment]
> Hello @a-goo You specified MetadataEndPoint and ImportTrustCertificate in the cmdlet run, however those parameters are from different parameter sets, so you either use ImportTrustCertificate or MetadataEndPoint

Thanks for the clarification. 
The documentation clearly needs this clarification added. As is stands, the documentation of the parameter for -MetadataEndPoint simple specifies that it's required, but not clearly which of the commands it is required for. Maybe separate the parameter sets into two different sections to improve clarity?
Please also clarify what the MetadataEndPoint URI is, the documentation has no description text. 

Also, additional examples would be good for different scenarios.

-------

So, from your feedback, I reran the command without the MetadataEndPoint parameter. And it failed:

![image](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/assets/105272899/08699274-b593-4da5-85e9-c0ed1d226525)

What's missing?

**Comment by get-itips** [comment]
> The documentation clearly needs this clarification added. 

The documentation already has 2 different parameter sets where you can see those parameters are in different param sets.

From the error you receive it says you need to run PowerShell elevated with administrator rights.

I'll add the description through a PR.

Thank you

**Comment by a-goo** [comment]
> From the error you receive it says you need to run PowerShell elevated with administrator rights.

Well, actually the error itself doesn't indicate a permissions issue. 
The standard warning suggests "**IF** you need to need to perform tasks that require elevated Administrator rights..."

And running the ISE with elevated admin rights makes no difference. It throws the same error:

![image](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/assets/105272899/b9caf862-5031-40e3-9081-44d24267bea8)
