### ISSUE TITLE
-The EnableAutoExpirationVersionTrim parameter is currently unavailable.

### ISSUE THREAD

**Issue by nakamae1983** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#482]
[Enter feedback here]
"-EnableAutoExpirationVersionTrim" parameter is currently not available.

The "-EnableAutoExpirationVersionTrim" parameter in the following URL is currently unavailable.
https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps#-enableautoexpirationversiontrim

The following message is displayed when the command is executed.
set-spotenant -EnableAutoExpirationVersionTrim $true
set-spotenant : The requested operation is part of a feature that is in private preview and will be available when the
The requested operation is part of a feature that is in private preview and will be available when the feature becomes generally available (GA).
![image](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/assets/65495605/dacbc0e9-4d10-447f-bcb0-4544e9b113a5)

Please add a comment to the docs that "this is a parameter that is not currently available" and the release date of this feature (URL of Microsoft 365 Roadmap).

 https://www.microsoft.com/ja-jp/microsoft-365/roadmap?filters=&searchterms=145802 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: da2c76d9-43fd-c631-e6d4-69852b376444
* Version Independent ID: b8ae322e-d3a7-9759-8407-b20f7469cad7
* Content: [Set-SPOTenant (Microsoft.Online.SharePoint.PowerShell)](https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps#-enableautoexpirationversiontrim)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by nakamae1983** [comment]
As stated in the Roadmap, this feature is scheduled for general availability in March 2024.
Please state when the feature will be available so that users do not misunderstand.

https://www.microsoft.com/ja-jp/microsoft-365/roadmap?filters=&searchterms=145802
![image](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/assets/65495605/38cb3301-f3f1-4e47-80d9-4592802afa93)

**Comment by get-itips** [comment]
Thanks for your feedback!
