### ISSUE TITLE
Set-SPOStorageEntity : Unknown Error

### ISSUE THREAD

**Issue by raguravindran** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#483]
Have been trying to run this command I keep getting this error

PS C:\windows\system32> Set-SPOStorageEntity -Site "https://pamainc-admin.sharepoint.com/sites/appcatalog" -Key "params" -Value '{"client_id":"123123"}' -Comments "comments" -Description "description"
Set-SPOStorageEntity : Unknown Error
At line:1 char:1
+ Set-SPOStorageEntity -Site "https://pamainc-admin.sharepoint.com/site ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-SPOStorageEntity], ServerException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.ServerException,Microsoft.Online.SharePoint.PowerShell.SetStorageEntity

===============================================================================================
**Version information**
PS C:\windows\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.3770
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.3770
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Name                                   Version
----                                   -------
Microsoft.Online.SharePoint.PowerShell 16.0.23814.12000

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c86c337e-0662-b777-d265-9c25e52618ef
* Version Independent ID: 96af1e2e-12d2-fc36-8870-1f35fa8cf380
* Content: [Set-SPOStorageEntity (Microsoft.Online.SharePoint.PowerShell)](https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/set-spostorageentity?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOStorageEntity.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOStorageEntity.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by raguravindran** [comment]
Tried samples given here yet, it did not work for us. Looking for some pointers here

https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/set-spostorageentity?view=sharepoint-ps

**Comment by get-itips** [comment]
Hello @raguravindran 
I see that in the url you published, you used the admin one? is that the correct url?

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and digging deep into it.  @raguravindran We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
