### ISSUE TITLE
This article is missing a step and doesn't work in Azure. 

### ISSUE THREAD

**Issue by enigmanet** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#505]
[Enter feedback here]

1st Issue.
--------------------------------
Once you install the module, i.e. 
Install-Module -Name Microsoft.Online.SharePoint.PowerShell

It's nice and dandy, 

Get-Module -Name Microsoft.Online.SharePoint.PowerShell -ListAvailable | Select Name,Version
Name                                   Version
----                                   -------
Microsoft.Online.SharePoint.PowerShell 16.0.23914.12000

2nd Issue.
--------------------------------
You need to clarify that this might not work in Azure Shell (bash or PowerShell) as that's based on linux and this module requires Windows to work per error code. 

![image](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/assets/81671144/7dd43fed-a507-4d01-a168-74c4ee44275c)

_I am able to repro, and wonder if you can also repro the issue.  This is not a OOB out of box, module, and was installed manually.  
The Microsoft.Online.SharePoint.PowerShell module will not work or don’t think it will work in Azure Cloud Shell because it depends on the Microsoft.Win32.Registry type, which is not available in Azure Cloud Shell. Azure Cloud Shell is a cloud-based environment and does not have access to the Windows registry, we just need to confirm that._

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51a2a070-5965-61d1-62e6-433fad2b5ecf
* Version Independent ID: d54bbe0a-37b6-a6f0-0b25-e931ac537d58
* Content: [Get started with the SharePoint Online Management Shell](https://learn.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?view=sharepoint-ps)
* Content Source: [sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @enigmanet 

In the Intro and Get Started articles it is mentioned it is a **Windows PowerShell** module.
And in the documentation for Cloud Shell it is mentioned is based on Linux.

Thanks for your feedback,

**Comment by enigmanet** [comment]
> 

Thank you for the reply, for the needy ones, out there, a work around that would work is to use the PnP Module inside the Azure Shell.
