### ISSUE TITLE
Value 3650 is wrong?!

### ISSUE THREAD

**Issue by SharePointainia** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#509]
Maybe you have a type...do you mean 365 oder really mean 3650 Days? --> OrphanedPersonalSitesRetentionPeriod 

https://learn.microsoft.com/de-de/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps#-orphanedpersonalsitesretentionperiod

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er wird für die Verknüpfung von learn.microsoft.com zum GitHub-Issue benötigt.*

* ID: da2c76d9-43fd-c631-e6d4-69852b376444
* Version Independent ID: b8ae322e-d3a7-9759-8407-b20f7469cad7
* Content: [Set-SPOTenant (Microsoft.Online.SharePoint.PowerShell)](https://learn.microsoft.com/de-de/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Hello @SharePointainia 
How are you?
That's the range according to the cmdlet's output

> set-spotenant : OrphanedPersonalSitesRetentionPeriod must have a value between 30 and 3650

**Comment by SharePointainia** [comment]
Okay Thank you, thought it was a typo 😎✌🏻
________________________________
Von: Andres Mariano Gorzelany ***@***.***>
Gesendet: Thursday, September 7, 2023 6:10:23 PM
An: MicrosoftDocs/OfficeDocs-SharePoint-PowerShell ***@***.***>
Cc: SharePointainia ***@***.***>; Mention ***@***.***>
Betreff: Re: [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell] Value 3650 is wrong?! (Issue #509)


Hello @SharePointainia<https://github.com/SharePointainia>
How are you?
That's the range according to the cmdlet's output

set-spotenant : OrphanedPersonalSitesRetentionPeriod must have a value between 30 and 3650
