### ISSUE TITLE
Which DomainGuids do we need ?

### ISSUE THREAD

**Issue by 361b3rn3** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#510]
DomainGuids  
- User
- Computer
- Both

Based on the article, [Case of the OneDrive for Business “Sorry can’t add your folder right now”](https://chentiangemalc.wordpress.com/2017/05/21/case-of-the-onedrive-for-business-sorry-cant-add-your-folder-right-now/) , it should be the computer domain.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68bf28c2-3265-5228-01f2-a3595a750abd
* Version Independent ID: d7cbfaf9-6af0-fd33-406e-7c0c194b5072
* Content: [Get-SPOTenantSyncClientRestriction (Microsoft.Online.SharePoint.PowerShell)](https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/get-spotenantsyncclientrestriction?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantSyncClientRestriction.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantSyncClientRestriction.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Hello @361b3rn3 how are you?

Please let me know if I understood correctly, in the article for https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenantsyncclientrestriction?view=sharepoint-ps it says it should be the domain guid, and yes, one of the methods to get it is PowerShell, is there any fix required to the article?

Thank you

**Comment by 361b3rn3** [comment]
Understood. 
Thank you!

**Comment by get-itips** [comment]
That's also noted here https://learn.microsoft.com/en-us/sharepoint/allow-syncing-only-on-specific-domains

I'll propose to add that to the cmdlet's article too

Thanks,

**Comment by 361b3rn3** [comment]
Great ! @get-itips,  your are the best.
Thank you.
