### ISSUE TITLE
Incorrect path in PS code

### ISSUE THREAD

**Issue by qcloudadmin** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#512]
This is a small issue but tripped me up when I was copying and pasting the PS code.

The path should be "sites", not "site":

Incorrect: https://<tenant>.sharepoint.com/site/samplesite

Correct: https://<tenant>.sharepoint.com/**sites**/samplesite

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f36c1f06-85b4-9a6a-28fc-115522dcb1c4
* Version Independent ID: 7e041b3f-dffb-00bf-c00d-b9b071a7b99a
* Content: [Start-SPOSiteRename (Microsoft.Online.SharePoint.PowerShell)](https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/start-spositerename?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteRename.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteRename.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Thanks for feedback
