### ISSUE TITLE
Broken hyperlink for timezone reference on new-sposite page

### ISSUE THREAD

**Issue by obhayes** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#514]
The link shown here

https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/new-sposite?view=sharepoint-ps#-timezoneid

is broken, when you click on "see SPRegionalSettings.TimeZones Property."

please correct
thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cbfbe213-47b7-f653-c8de-77aef5d2c959
* Version Independent ID: 171e4cb3-5d5e-80bf-c2e2-df4adf1eaaeb
* Content: [New-SPOSite (Microsoft.Online.SharePoint.PowerShell)](https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/new-sposite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/New-SPOSite.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/New-SPOSite.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
PR Created, thank you!
