### ISSUE TITLE
SiteOwnerManageLegacyServicePrincipalEnabled documentation needs to be clarified

### ISSUE THREAD

**Issue by davidwilborn** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#526]
For SiteOwnerManageLegacyServicePrincipalEnabled documentation, it states:

"When the value is set to false, the service principal can only be created or updated by the SharePoint tenant admin. If the value is set to true, both the SharePoint tenant admin and site collection admin will be able to create or update the service principal through SharePoint."

This is ambiguous, and seems to say that Tenant Admins can create or modify the service principal at the Site Collection level when SiteOwnerManageLegacyServicePrincipalEnabled is set to "false" but this is not the case. What the parameter appears to do is disable using AppRegNew.aspx and AppInv.aspx at the Site Collection level for all users, regardless of whether or not they are Tenant Admins.

AppRegNew.aspx and AppInv.aspx at the Tenant level, e.g. https://contoso-admin.sharepoint.com/_layouts/15/AppRegNew.aspx are still available, even if SiteOwnerManageLegacyServicePrincipalEnabled is set to "false". So SharePoint Admins can still register apps or update app permissions but at the Tenant level only.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: da2c76d9-43fd-c631-e6d4-69852b376444
* Version Independent ID: b8ae322e-d3a7-9759-8407-b20f7469cad7
* Content: [Set-SPOTenant (Microsoft.Online.SharePoint.PowerShell)](https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Hello @davidwilborn I'm working on this

**Comment by Itzafineday** [comment]
This property appears to be unavailable in the current version of the Sharepoint Management Shell. It is referenced by other current Microsoft documentation and no workaround is apparently available.

**Comment by davidwilborn** [comment]
@Itzafineday - the property is available as of version 16.0.24009.0 of SharePoint Management Shell: 
![image](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/assets/16227149/4991e69c-111e-45ed-97ff-f217504c9eec)

**Comment by yogkumgit** [comment]
@get-itips

**Comment by get-itips** [comment]
Hello
I've got information from the team, _due to customer feedback SharePoint Tenant admins will be able to do the actions in the normal site collection level even when the flag is false. And it will start to roll out._

So the article does not need an update.
Hope this information helps you,

Thank you!
