### ISSUE TITLE
Bad Template ID -- Topic | a30fef54-a4e5-4beb-a8b5-962c528d753a

### ISSUE THREAD

**Issue by jpatel1002** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#544]
Communication site templates:
Correct Template ID for Topic  | 96c933ac-3698-44c7-9f4a-5fd17d71af9e

Please update document.

**Comment by yogkumgit** [comment]
@jpatel1002 Please indicate the document you are referring to and wish to give the feedback for its improvement. Thanks

**Comment by yogkumgit** [comment]
@jpatel1002 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
