### ISSUE TITLE
Organizational Assets Library - Public Display name (in Office) is Tenant name

### ISSUE THREAD

**Issue by Finklesdata** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#545]
Under the description, this is apparently incorrect: "The name publicly displayed for the library will be the name of the library on the SharePoint site".

Advice below is that sharepoint references the title field for the library, which appears to be only set via Set-PnPList.

See: 
https://answers.microsoft.com/en-us/msoffice/forum/all/sharepoint-organizational-asset-library-public/967e19f7-3fae-4b80-84cb-5594a47bcb6f

The publicly displayed name in office for the library is our Azure Tenant name.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 58fd3557-6ef6-28db-1272-26655baeb9dd
* Version Independent ID: 49575a24-f38b-231b-1577-401199c97384
* Content: [Add-SPOOrgAssetsLibrary (Microsoft.Online.SharePoint.PowerShell)](https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/add-spoorgassetslibrary?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Add-SPOOrgAssetsLibrary.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOOrgAssetsLibrary.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @Maralesfahanpoor
* Microsoft Alias: **maesfaha**

**Comment by get-itips** [comment]
Thanks for your feedback
