### ISSUE TITLE
Missing details on multi-geo

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#550]
Please add details on configuration needed for multi-geo organizations. This article refers to the tenant, but it seems this is not tenant wide. This is a per-geo configuration and the library can't be shared across geos.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 58fd3557-6ef6-28db-1272-26655baeb9dd
* Version Independent ID: 49575a24-f38b-231b-1577-401199c97384
* Content: [Add-SPOOrgAssetsLibrary (Microsoft.Online.SharePoint.PowerShell)](https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/add-spoorgassetslibrary?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Add-SPOOrgAssetsLibrary.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOOrgAssetsLibrary.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @Maralesfahanpoor
* Microsoft Alias: **maesfaha**

**Comment by get-itips** [comment]
Hello @danmyhre Dan, I'm working on this.

**Comment by yogkumgit** [comment]
@get-itips Please update. Thanks
