### ISSUE TITLE
Access Denied Error - Solution Identified

### ISSUE THREAD

**Issue by BlueOdyssey** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#564]
Can I suggest adding in a note about requiring a SharePoint Online license to be assigned to the account used to execute either Get-SPOTenant or Set-SPOTenant? Recently had a support case (can provide the case ID) where, without the license assigned, the administrator would receive the error `Access is denied. (Exception from from HRESULT: 0x80070005 (E_ACCESSDENIED))`

Resolution to the error was to assign the user a license - it then worked straightaway. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d752d7a6-bd6b-8f78-6db8-92f4b35da5bf
* Version Independent ID: 6d445714-6900-7465-2eb9-8cc6e7410191
* Content: [Get-SPOTenant (Microsoft.Online.SharePoint.PowerShell)](https://learn.microsoft.com/en-us/powershell/module/sharepoint-online/get-spotenant?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenant.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenant.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Hello @BlueOdyssey how are you?
I've just used an unlicensed user in a lab tenant, assigned SPO Admin Role, and connected and I could run Get and Set-SPOTenant cmdlets
Many thanks for your feedback,

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @BlueOdyssey Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
