### ISSUE TITLE
Get-FileSensitivityLabelInfo wrong ProtectionEnabled status

### ISSUE THREAD

**Issue by SchmidSP** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#63]
AIP Supported Filetypes (see: https://docs.microsoft.com/de-de/azure/information-protection/rms-client/clientv2-admin-guide-file-types) has wrong ProtectionEnabled Status.

See Example with vsdx and pdf

Example:
PS C:\Users\xx> Get-FileSensitivityLabelInfo -Fileurl "https://xxx/teams/Kunden-Info-Team/Freigegebene Dokumente/Kunden/2test.vsdx"

LabelId DisplayName ProtectionEnabled ParentLabelId
------- ----------- ----------------- -------------
                                False

PS C:\Users\xx> Get-FileSensitivityLabelInfo -Fileurl "https://xxx/teams/Kunden-Info-Team/Freigegebene Dokumente/Kunden/1test.pdf"

LabelId DisplayName ProtectionEnabled ParentLabelId
------- ----------- ----------------- -------------
                                False

**Comment by get-itips** [comment]
Hello @SchmidSP 
How are you? Hope you are doing well.

I read your comment and I couldn't fully understand, would you mind specifying the article under OfficeDocs-SharePoint-PowerShell / https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/ that you think needs a correction?

Thank you!

**Comment by SchmidSP** [comment]
Hi,

in https://docs.microsoft.com/de-de/azure/information-protection/rms-client/clientv2-admin-guide-file-types)
supportet Filetypes are reportet (for example pdf).
But Powershell commands don't support this filetypes.

So you can change the docs article or give the powershell team a hint that they fix the powershell commands.

**Comment by get-itips** [comment]
Hello @SchmidSP 
Thanks for clarifying.
I assume there is a label applied for the .pdf file in your scenario.
I am not sure if the `Get-FileSensitivityLabelInfo` supports displaying the label for portable document format as the article for it mentions _office online files_, will try to check and return.

Thanks

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @SchmidSP Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
