### ISSUE TITLE
Only works on classic pages

### ISSUE THREAD

**Issue by zumiek** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#73]
This command only returns values if it's a classic page. It does not work on modern pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fc6bb84-4cf7-157b-6a35-82493d0dcd05
* Version Independent ID: 9058c992-efb6-40fc-a6ee-e22fab1862af
* Content: [Get-PnPWebPart (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpwebpart?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPWebPart.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPWebPart.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @zumiek 

how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by tiburd** [comment]
Because this issue needs to be opened in a different repo, we're closing this issue.

Thank you!
