### ISSUE TITLE
Help collections in SharePoint Server 2019

### ISSUE THREAD

**Issue by SharePointBlackBelt** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#79]
The article says is applies to SharePoint Server (doesn't indicate a specific version), but when I execute this PS on a SharePoint Server 2019 farm, it returns help collections for SharePoint 2010.

Get-SPHelpCollection

Title                                                    Name
-----                                                    ----
Central Administration Help                              OSSCentralAdmin.1033.15
SharePoint Help                                          OSSEndUser.1033.15
SharePoint Foundation 2010                               WSSEndUser.1033.12
SharePoint Server 2010                                   OSSEndUser.1033.12
SharePoint Foundation 2010 Central Administration        WSSCentralAdmin.1033.12
Project Web App Help                                     PSEndUser.1033.15
SharePoint Help                                          WSSEndUser.1033.15
Central Administration Help                              WSSCentralAdmin.1033.15
SharePoint Server 2010 Central Administration            OSSCentralAdmin.1033.12
PerformancePoint Dashboard Designer 2010 Help and How-to DashboardDesigner.1033.12

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c976e38e-b1f7-0aba-ce6a-0cc4e6dcbec3
* Version Independent ID: bf3a4231-c441-22ce-b4f2-b3151bc1c935
* Content: [Get-SPHelpCollection (sharepoint-server)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/get-sphelpcollection?view=sharepoint-server-ps)
* Content Source: [sharepoint/sharepoint-server-ps/sharepoint-server/Get-SPHelpCollection.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-server-ps/sharepoint-server/Get-SPHelpCollection.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @SharePointBlackBelt Vincent, how are you?

That functionality is deprecated you can read more here https://docs.microsoft.com/en-us/sharepoint/what-s-new/what-s-deprecated-or-removed-from-sharepoint-server-2019#custom-help

All cmdlet articles had been updated in the applies to metadata, even though it is deprecated, as the cmdlet is still there.

Hope this information helps you,

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @SharePointBlackBelt Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
