### ISSUE TITLE
Remove-PnPFile does not support -WhatIf parameter

### ISSUE THREAD

**Issue by bsimser** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#81]
Documentation says you can use -WhatIf as parameter. This is a good thing for any PowerShell cmdlet. 

It's listed in the parameters but not in the syntax section. If you try to use it you get the error message:

`Remove-PnPFile : A parameter cannot be found that matches parameter named 'WhatIf'.`

It should either support it or remove it from the documentation.

**Comment by get-itips** [comment]
Hello @bsimser 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @bsimser Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
