### ISSUE TITLE
Invoke-PnPSiteTemplate issue in DoD

### ISSUE THREAD

**Issue by MSGRRojas** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#83]
Trying to get the Invoke-PnPSiteTemplate to work in DoD and getting the following error:

{"error_description":"Exception of type 'Microsoft.IdentityModel.Tokens.AudienceUriValidationFailedException' was thrown"}

Not sure how or why this is happening but we can't seem to apply a .pnp template

**Comment by get-itips** [comment]
Hello @MSGRRojas 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @MSGRRojas Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
