### ISSUE TITLE
Set Managed Metadata Value Not Working

### ISSUE THREAD

**Issue by taylorSteeleIntergen** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#85]
Unable to set managed metadata value on document set. 

The following code is not working as expected:
Set-PnPListItem -List "Shared Documents" -Identity $documentSet.FieldValues.ID -Values @{"BusinessUnit" = "$businessUnitGUID"}

BusinessUnit is a managed metadata column linked to a term set. The businessUnitGUID is fetched using another function. 

No error is shown but the value is not set. I have checked the term GUID and internal name, both are correct. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69beaee4-cf0c-4bc4-1c8e-2e5a3a03f20a
* Version Independent ID: 7036d101-df3f-35d3-3eff-9e1253fd1387
* Content: [Set-PnPListItem (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnplistitem?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPListItem.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-pnp/Set-PnPListItem.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @taylorSteeleIntergen 

how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @taylorSteeleIntergen Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
