### ISSUE TITLE
Incorrect name for Get-PnPSubWeb - should be Get-PnPSubWebs

### ISSUE THREAD

**Issue by ANovitsky** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#86]
Incorrect, should be **Get-PnPSubWebs** istead of **Get-PnPSubWeb**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22863701-6bf5-05be-6815-af6110a03776
* Version Independent ID: f95f9ec3-d51b-a7f9-a65c-31974f5d5a1d
* Content: [Get-PnPSubWeb (PnP.Powershell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpsubweb?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPSubWeb.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPSubWeb.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **pamgreen**

**Comment by get-itips** [comment]
Hello @ANovitsky 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @ANovitsky Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
