### ISSUE TITLE
Missing Certificate parameter for New-SPWebApplication

### ISSUE THREAD

**Issue by ykuijs** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#90]
With SharePoint Subscription Edition, New-SPWebApplication has a new Certificate parameter. Unfortunately the documentation is not yet updated to include this parameter:
https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/new-spwebapplication?view=sharepoint-server-ps

https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-server-ps/sharepoint-server/New-SPWebApplication.md

Could this documentation be updated?

**Comment by TroyStarr** [comment]
Good catch, I believe this has already been fixed by #72.  Please take a look and let us know if you still have any concerns.  Thanks!

**Comment by ykuijs** [comment]
Hi @TroyStarr, you are absolutely right. That PR has been merged 16 hours ago, which has updated the Docs pages.

So this issue is no longer relevant! Closing the issue

Thanks for the update!
