### ISSUE TITLE
-Filter Parameter of Get-SPOSite

### ISSUE THREAD

**Issue by MelissaAE** [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell#99]
The -Filter parameter of the Get-SPOSite cmdlet used in the SharePoint Online PS module isn't working.  It errors to: "The term '-Filter' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70048c8b-cd6e-b20a-b9e4-7e5ed781cc29
* Version Independent ID: 9cfa221c-259a-633d-e176-32ffc17e085e
* Content: [Get-SPOSite (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-sposite?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSite.md](https://github.com/MicrosoftDocs/OfficeDocs-Sharepoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSite.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by get-itips** [comment]
Hello @MelissaAE Melissa,

It works for me, what version of the Module are you using?

![image](https://user-images.githubusercontent.com/36666927/144892669-23b2996c-8cfe-4046-959e-8f19f4c067a5.png)

**Comment by yogkumgit** [comment]
@get-itips Thank you very much for the contribution and sharing this explanation. @MelissaAE Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
